enum HarnessMonitorUITestAccessibility {
  static let appChromeRoot = "harness.app.chrome"
  static let appChromeState = "harness.app.chrome.state"
  static let toolbarChromeState = "harness.toolbar.chrome.state"
  static let toolbarBaselineDivider = "harness.toolbar.baseline-divider"
  static let persistenceBanner = "harness.persistence.banner"
  static let persistedDataBanner = "harness.persisted-data.banner"
  static let persistedDataBannerFrame = "harness.persisted-data.banner.frame"
  static let sessionStatusBanner = "harness.session-status.banner"
  static let daemonCard = "harness.sidebar.daemon-card"
  static let daemonCardFrame = "harness.sidebar.daemon-card.frame"
  static let sidebarShellFrame = "harness.sidebar.shell.frame"
  static let navigateBackButton = "harness.toolbar.navigate-back"
  static let navigateForwardButton = "harness.toolbar.navigate-forward"
  static let toolbarCenterpiece = "harness.toolbar.centerpiece"
  static let toolbarCenterpieceFrame = "harness.toolbar.centerpiece.frame"
  static let toolbarCenterpieceState = "harness.toolbar.centerpiece.state"
  static let toolbarCenterpieceMode = "harness.toolbar.centerpiece.mode"
  static let toolbarCenterpieceMetricsFrame = "harness.toolbar.centerpiece.metrics.frame"
  static let toolbarStatusTicker = "harness.toolbar.status-ticker"
  static let toolbarStatusTickerFrame = "harness.toolbar.status-ticker.frame"
  static let toolbarStatusTickerContentFrame = "harness.toolbar.status-ticker.content.frame"
  static let toolbarStatusTickerHoverFrame = "harness.toolbar.status-ticker.hover.frame"
  static let preferencesButton = "harness.toolbar.preferences"
  static let refreshButton = "harness.toolbar.refresh"
  static let inspectorToggleButton = "harness.toolbar.inspector-toggle"
  static let sidebarStartButton = "harness.sidebar.action.start"
  static let sidebarInstallButton = "harness.sidebar.action.install"
  static let sidebarStartButtonFrame = "harness.sidebar.action.start.frame"
  static let sidebarInstallButtonFrame = "harness.sidebar.action.install.frame"
  static let sidebarDaemonStatusBadge = "harness.sidebar.daemon-status-badge"
  static let sidebarLaunchdStatusIcon = "harness.sidebar.daemon-launchd-icon"
  static let sidebarRoot = "harness.sidebar.root"
  static let previewProjectHeader = "harness.sidebar.project-header.project-6ccf8d0a"
  static let previewProjectHeaderFrame = "harness.sidebar.project-header.project-6ccf8d0a.frame"
  static let previewSessionRow = "harness.sidebar.session.sess-harness"
  static let previewSessionRowFrame = "harness.sidebar.session.sess-harness.frame"
  static let overflowSessionRow = "harness.sidebar.session.sess-harness-17"
  static let previewSessionTitle =
    "Track all live multi-agent harness sessions from a macOS cockpit"
  static let sidebarEmptyState = "harness.sidebar.empty-state"
  static let sidebarEmptyStateFrame = "harness.sidebar.empty-state.frame"
  static let sidebarEmptyStateTitle = "No sessions indexed yet"
  static let sidebarSessionList = "harness.sidebar.session-list"
  static let sidebarSessionListContent = "harness.sidebar.session-list.content"
  static let sidebarFiltersCard = "harness.sidebar.filters"
  static let sidebarFiltersCardFrame = "harness.sidebar.filters.frame"
  static let sessionFilterGroup = "harness.sidebar.filter-group"
  static let sidebarSearchField = "harness.sidebar.search"
  static let sidebarClearFiltersButton = "harness.sidebar.filters.clear"
  static let sidebarClearSearchHistoryButton = "harness.sidebar.search.clear-history"
  static let sidebarSortPicker = "harness.sidebar.picker.sort"
  static let sidebarFocusPicker = "harness.sidebar.picker.focus"
  static let activeFilterButton = "harness.sidebar.filter.active"
  static let allFilterButton = "harness.sidebar.filter.all"
  static let endedFilterButton = "harness.sidebar.filter.ended"
  static let openWorkChip = "harness.sidebar.focus-chip.openwork"
  static let blockedChip = "harness.sidebar.focus-chip.blocked"
  static let observedChip = "harness.sidebar.focus-chip.observed"
  static let idleChip = "harness.sidebar.focus-chip.idle"
  static let onboardingCard = "harness.board.onboarding-card"
  static let onboardingCardFrame = "harness.board.onboarding-card.frame"
  static let onboardingStartButton = "harness.board.action.start"
  static let onboardingInstallButton = "harness.board.action.install"
  static let onboardingRefreshButton = "harness.board.action.refresh"
  static let onboardingStartButtonFrame = "harness.board.action.start.frame"
  static let onboardingInstallButtonFrame = "harness.board.action.install.frame"
  static let onboardingRefreshButtonFrame = "harness.board.action.refresh.frame"
  static let sessionsBoardRoot = "harness.board.root"
  static let recentSessionsCard = "harness.board.recent-sessions-card"
  static let recentSessionsCardFrame = "harness.board.recent-sessions-card.frame"
  static let contentRootFrame = "harness.content.root.frame"
  static let inspectorRoot = "harness.inspector.root"
  static let inspectorEmptyState = "harness.inspector.empty-state"
  static let sessionInspectorCard = "harness.inspector.session-card"
  static let taskInspectorCard = "harness.inspector.task-card"
  static let taskNoteField = "harness.inspector.task-note-field"
  static let taskNoteAddButton = "harness.inspector.task-note-add"
  static let taskNotesUnavailable = "harness.inspector.task-notes-unavailable"
  static let agentInspectorCard = "harness.inspector.agent-card"
  static let signalInspectorCard = "harness.inspector.signal-card"
  static let observerInspectorCard = "harness.inspector.observer-card"
  static let actionActorPicker = "harness.inspector.action-actor"
  static let signalCommandField = "harness.inspector.signal-command"
  static let signalMessageField = "harness.inspector.signal-message"
  static let removeAgentButton = "harness.inspector.remove-agent"
  static let signalSendButton = "harness.inspector.signal-send"
  static let observeSummaryButton = "harness.session.observe.summary"
  static let endSessionButton = "harness.session.action.end"
  static let pendingLeaderTransferCard = "harness.session.pending-transfer"
  static let taskUICard = "harness.session.task.task-ui"
  static let taskRoutingCard = "harness.session.task.task-routing"
  static let leaderAgentCard = "harness.session.agent.leader-claude"
  static let workerAgentCard = "harness.session.agent.worker-codex"
  static let preferencesRoot = "harness.preferences.root"
  static let preferencesState = "harness.preferences.state"
  static let preferencesPanel = "harness.preferences.panel"
  static let preferencesSidebar = "harness.preferences.sidebar"
  static let preferencesBackButton = "harness.preferences.nav.back"
  static let preferencesForwardButton = "harness.preferences.nav.forward"
  static let preferencesTitle = "harness.preferences.title"
  static let preferencesThemeModePicker = "harness.preferences.theme-mode"
  static let preferencesBackdropModePicker = "harness.preferences.backdrop-mode"
  static let preferencesBackgroundGallery = "harness.preferences.background-gallery"
  static let preferencesTextSizePicker = "harness.preferences.text-size"
  static let preferencesTimeZoneModePicker = "harness.preferences.time-zone-mode"
  static let preferencesCustomTimeZonePicker = "harness.preferences.custom-time-zone"
  static let preferencesGeneralSection = "harness.preferences.section.general"
  static let preferencesAppearanceSection = "harness.preferences.section.appearance"
  static let preferencesConnectionSection = "harness.preferences.section.connection"
  static let preferencesDatabaseSection = "harness.preferences.section.database"
  static let preferencesDiagnosticsSection = "harness.preferences.section.diagnostics"
  static let preferencesDatabaseStatistics = "harness.preferences.database.statistics"
  static let preferencesDatabaseOperations = "harness.preferences.database.operations"
  static let preferencesDatabaseHealth = "harness.preferences.database.health"
  static let refreshStatisticsButton = "harness.preferences.action.refresh-statistics"
  static let clearSessionCacheButton = "harness.preferences.action.clear-session-cache"
  static let clearSearchHistoryPrefsButton = "harness.preferences.action.clear-search-history"
  static let clearUserDataButton = "harness.preferences.action.clear-user-data"
  static let clearAllDataButton = "harness.preferences.action.clear-all-data"
  static let revealInFinderButton = "harness.preferences.action.reveal-in-finder"
  static let persistenceMetric = "harness.preferences.metric.persistence"
  static let schemaVersionMetric = "harness.preferences.metric.schema-version"
  static let cachedSessionsMetric = "harness.preferences.metric.cached-sessions"
  static let cachedProjectsMetric = "harness.preferences.metric.cached-projects"
  static let preferencesEndpointCard = "harness.preferences.metric.endpoint"
  static let preferencesVersionCard = "harness.preferences.metric.version"
  static let preferencesLaunchdCard = "harness.preferences.metric.launchd"
  static let preferencesDatabaseSizeCard = "harness.preferences.metric.database-size"
  static let preferencesLiveSessionsCard = "harness.preferences.metric.live-sessions"
  static let reconnectButton = "harness.preferences.action.reconnect"
  static let refreshDiagnosticsButton = "harness.preferences.action.refresh-diagnostics"
  static let startDaemonButton = "harness.preferences.action.start-daemon"
  static let installLaunchAgentButton = "harness.preferences.action.install-launch-agent"
  static let removeLaunchAgentButton = "harness.preferences.action.remove-launch-agent"
  static let actionToast = "harness.action-toast"

  static func preferencesBackgroundTile(_ key: String) -> String {
    "harness.preferences.background.\(slug(key))"
  }

  static func sidebarSortSegment(_ order: String) -> String {
    "harness.sidebar.sort.\(slug(order))"
  }

  static func sidebarFocusChip(_ filter: String) -> String {
    "harness.sidebar.focus-chip.\(slug(filter))"
  }

  private static func slug(_ value: String) -> String {
    let lowercased = value.lowercased()
    return
      lowercased
      .replacing(" ", with: "-")
      .replacing("_", with: "-")
      .replacing(":", with: "-")
      .replacing("/", with: "-")
      .replacing(".", with: "")
  }
}
