enum HarnessMonitorUITestAccessibility {
  static let appChromeRoot = "harness.app.chrome"
  static let appChromeState = "harness.app.chrome.state"
  static let auditBuildState = "harness.audit.build.state"
  static let auditBuildBadge = "harness.audit.build.badge"
  static let perfScenarioState = "harness.perf.scenario.state"
  static let toolbarChromeState = "harness.toolbar.chrome.state"
  static let toolbarBaselineDivider = "harness.toolbar.baseline-divider"
  static let persistenceBanner = "harness.persistence.banner"
  static let persistedDataBanner = "harness.persisted-data.banner"
  static let persistedDataBannerFrame = "harness.persisted-data.banner.frame"
  static let sessionStatusBanner = "harness.session-status.banner"
  static let sidebarShellFrame = "harness.sidebar.shell.frame"
  static let navigateBackButton = "harness.toolbar.navigate-back"
  static let navigateForwardButton = "harness.toolbar.navigate-forward"
  static let toolbarCenterpiece = "harness.toolbar.centerpiece"
  static let toolbarCenterpieceFrame = "harness.toolbar.centerpiece.frame"
  static let toolbarCenterpieceState = "harness.toolbar.centerpiece.state"
  static let toolbarCenterpieceMode = "harness.toolbar.centerpiece.mode"
  static let toolbarCenterpieceMetricsFrame = "harness.toolbar.centerpiece.metrics.frame"
  static let toolbarStartDaemonButton = "harness.toolbar.action.start"
  static let toolbarStatusTicker = "harness.toolbar.status-ticker"
  static let toolbarStatusTickerFrame = "harness.toolbar.status-ticker.frame"
  static let toolbarStatusTickerContentFrame = "harness.toolbar.status-ticker.content.frame"
  static let refreshButton = "harness.toolbar.refresh"
  static let inspectorToggleButton = "harness.toolbar.inspector-toggle"
  static let sidebarRoot = "harness.sidebar.root"
  static let previewProjectHeader = "harness.sidebar.project-header.project-6ccf8d0a"
  static let previewProjectHeaderFrame = "harness.sidebar.project-header.project-6ccf8d0a.frame"
  static let previewCheckoutHeader = "harness.sidebar.worktree-header.project-6ccf8d0a"
  static let previewCheckoutHeaderFrame = "harness.sidebar.worktree-header.project-6ccf8d0a.frame"
  static let previewSessionRow = "harness.sidebar.session.sess-harness"
  static let previewSessionRowFrame = "harness.sidebar.session.sess-harness.frame"
  static let previewSessionRowSelectionFrame =
    "harness.sidebar.session.sess-harness.selection.frame"
  static let signalRegressionSecondarySessionRow = "harness.sidebar.session.sess-harness-secondary"
  static let previewSignalCard = "harness.session.signal.sig-ui-1"
  static let singleAgentSessionRow = "harness.sidebar.session.sess-harness-solo"
  static let overflowSessionRow = "harness.sidebar.session.sess-harness-17"
  static let previewSessionTitle =
    "Track all live multi-agent harness sessions from a macOS cockpit"
  static let sidebarEmptyState = "harness.sidebar.empty-state"
  static let sidebarEmptyStateFrame = "harness.sidebar.empty-state.frame"
  static let sidebarEmptyStateTitle = "No sessions indexed yet"
  static let sidebarSessionList = "harness.sidebar.session-list"
  static let sidebarSessionListContent = "harness.sidebar.session-list.content"
  static let sidebarFiltersCard = "harness.sidebar.filters"
  static let sidebarFiltersCardFrame = "harness.sidebar.filters.frame"
  static let sidebarFilterMenu = "harness.toolbar.sidebar-filters"
  static let sidebarFilterState = "harness.sidebar.filter.state"
  static let sessionFilterGroup = "harness.sidebar.filter-group"
  static let sidebarSearchField = "harness.sidebar.search"
  static let sidebarClearFiltersButton = "harness.sidebar.filters.clear"
  static let sidebarClearSearchHistoryButton = "harness.sidebar.search.clear-history"
  static let sidebarSortPicker = "harness.sidebar.picker.sort"
  static let sidebarFocusPicker = "harness.sidebar.picker.focus"
  static let activeFilterButton = "harness.sidebar.filter.active"
  static let allFilterButton = "harness.sidebar.filter.all"
  static let endedFilterButton = "harness.sidebar.filter.ended"
  static let openWorkChip = "harness.sidebar.focus-chip.openwork"
  static let blockedChip = "harness.sidebar.focus-chip.blocked"
  static let observedChip = "harness.sidebar.focus-chip.observed"
  static let idleChip = "harness.sidebar.focus-chip.idle"
  static let onboardingCard = "harness.board.onboarding-card"
  static let onboardingCardFrame = "harness.board.onboarding-card.frame"
  static let onboardingStartButton = "harness.board.action.start"
  static let onboardingInstallButton = "harness.board.action.install"
  static let onboardingRefreshButton = "harness.board.action.refresh"
  static let onboardingStartButtonFrame = "harness.board.action.start.frame"
  static let onboardingInstallButtonFrame = "harness.board.action.install.frame"
  static let onboardingRefreshButtonFrame = "harness.board.action.refresh.frame"
  static let sidebarStartButton = onboardingStartButton
  static let sidebarInstallButton = onboardingInstallButton
  static let sidebarStartButtonFrame = onboardingStartButtonFrame
  static let sidebarInstallButtonFrame = onboardingInstallButtonFrame
  static let sessionsBoardRoot = "harness.board.root"
  static let recentSessionsCard = "harness.board.recent-sessions-card"
  static let recentSessionsCardFrame = "harness.board.recent-sessions-card.frame"
  static let contentRootFrame = "harness.content.root.frame"
  static let inspectorRoot = "harness.inspector.root"
  static let inspectorEmptyState = "harness.inspector.empty-state"
  static let inspectorLoadingState = "harness.inspector.loading-state"
  static let sessionInspectorCard = "harness.inspector.session-card"
  static let taskInspectorCard = "harness.inspector.task-card"
  static let taskNoteField = "harness.inspector.task-note-field"
  static let taskNoteAddButton = "harness.inspector.task-note-add"
  static let taskNotesUnavailable = "harness.inspector.task-notes-unavailable"
  static let agentInspectorCard = "harness.inspector.agent-card"
  static let signalInspectorCard = "harness.inspector.signal-card"
  static let observerInspectorCard = "harness.inspector.observer-card"
  static let actionActorPicker = "harness.inspector.action-actor"
  static let signalCommandField = "harness.inspector.signal-command"
  static let signalMessageField = "harness.inspector.signal-message"
  static let createTaskTitleField = "harness.inspector.create-task.title"
  static let createTaskButton = "harness.inspector.create-task"
  static let assignTaskButton = "harness.inspector.assign-task"
  static let updateTaskQueuePolicyButton = "harness.inspector.update-task-queue-policy"
  static let updateTaskStatusButton = "harness.inspector.update-task-status"
  static let checkpointTaskButton = "harness.inspector.checkpoint-task"
  static let changeRoleButton = "harness.inspector.change-role"
  static let removeAgentButton = "harness.inspector.remove-agent"
  static let signalSendButton = "harness.inspector.signal-send"
  static let leaderTransferSection = "harness.inspector.leader-transfer"
  static let leaderTransferPicker = "harness.inspector.leader-transfer-picker"
  static let observeSummaryButton = "harness.session.observe.summary"
  static let observeSessionButton = "harness.session.action.observe"
  static let endSessionButton = "harness.session.action.end"
  static let pendingLeaderTransferCard = "harness.session.pending-transfer"
  static let taskDropQueueCard = "harness.session.task.task-drop-queue"
  static let taskUICard = "harness.session.task.task-ui"
  static let taskRoutingCard = "harness.session.task.task-routing"
  static let leaderAgentCard = "harness.session.agent.leader-claude"
  static let workerAgentCard = "harness.session.agent.worker-codex"
  static let preferencesRoot = "harness.preferences.root"
  static let preferencesState = "harness.preferences.state"
  static let preferencesPanel = "harness.preferences.panel"
  static let preferencesSidebar = "harness.preferences.sidebar"
  static let preferencesBackButton = "harness.preferences.nav.back"
  static let preferencesForwardButton = "harness.preferences.nav.forward"
  static let preferencesTitle = "harness.preferences.title"
  static let preferencesThemeModePicker = "harness.preferences.theme-mode"
  static let preferencesBackdropModePicker = "harness.preferences.backdrop-mode"
  static let preferencesBackgroundGallery = "harness.preferences.background-gallery"
  static let preferencesTextSizePicker = "harness.preferences.text-size"
  static let preferencesTimeZoneModePicker = "harness.preferences.time-zone-mode"
  static let preferencesCustomTimeZonePicker = "harness.preferences.custom-time-zone"
  static let preferencesGeneralSection = "harness.preferences.section.general"
  static let preferencesAppearanceSection = "harness.preferences.section.appearance"
  static let preferencesNotificationsSection = "harness.preferences.section.notifications"
  static let preferencesVoiceSection = "harness.preferences.section.voice"
  static let preferencesConnectionSection = "harness.preferences.section.connection"
  static let preferencesDatabaseSection = "harness.preferences.section.database"
  static let preferencesDiagnosticsSection = "harness.preferences.section.diagnostics"
  static let preferencesVoiceRoot = "harness.preferences.voice"
  static let preferencesVoiceLocaleField = "harness.preferences.voice.locale-field"
  static let preferencesVoiceLocalePicker = "harness.preferences.voice.locale-picker"
  static let preferencesVoiceLocalDaemonToggle = "harness.preferences.voice.local-daemon"
  static let preferencesVoiceAgentBridgeToggle = "harness.preferences.voice.agent-bridge"
  static let preferencesVoiceRemoteProcessorToggle = "harness.preferences.voice.remote-processor"
  static let preferencesVoiceRemoteProcessorURLField =
    "harness.preferences.voice.remote-processor-url"
  static let preferencesVoiceInsertionModePicker = "harness.preferences.voice.insertion-mode"
  static let preferencesVoiceAudioChunksToggle = "harness.preferences.voice.audio-chunks"
  static let preferencesVoicePendingAudioChunkLimitField =
    "harness.preferences.voice.pending-audio-limit"
  static let preferencesVoicePendingTranscriptLimitField =
    "harness.preferences.voice.pending-transcript-limit"
  static let preferencesVoiceStatus = "harness.preferences.voice.status"
  static let preferencesNotificationsStatus = "harness.preferences.notifications.status"
  static let preferencesNotificationsPresetPicker = "harness.preferences.notifications.preset"
  static let preferencesNotificationsCategoryPicker = "harness.preferences.notifications.category"
  static let preferencesNotificationsSoundPicker = "harness.preferences.notifications.sound"
  static let preferencesNotificationsAttachmentPicker =
    "harness.preferences.notifications.attachment"
  static let preferencesNotificationsTriggerPicker = "harness.preferences.notifications.trigger"
  static let preferencesNotificationsSendButton = "harness.preferences.notifications.send"
  static let preferencesDatabaseStatistics = "harness.preferences.database.statistics"
  static let preferencesDatabaseOperations = "harness.preferences.database.operations"
  static let preferencesDatabaseHealth = "harness.preferences.database.health"
  static let refreshStatisticsButton = "harness.preferences.action.refresh-statistics"
  static let clearSessionCacheButton = "harness.preferences.action.clear-session-cache"
  static let clearSearchHistoryPrefsButton = "harness.preferences.action.clear-search-history"
  static let clearUserDataButton = "harness.preferences.action.clear-user-data"
  static let clearAllDataButton = "harness.preferences.action.clear-all-data"
  static let revealInFinderButton = "harness.preferences.action.reveal-in-finder"
  static let persistenceMetric = "harness.preferences.metric.persistence"
  static let schemaVersionMetric = "harness.preferences.metric.schema-version"
  static let cachedSessionsMetric = "harness.preferences.metric.cached-sessions"
  static let cachedProjectsMetric = "harness.preferences.metric.cached-projects"
  static let preferencesEndpointCard = "harness.preferences.metric.endpoint"
  static let preferencesVersionCard = "harness.preferences.metric.version"
  static let preferencesLaunchdCard = "harness.preferences.metric.launchd"
  static let preferencesDatabaseSizeCard = "harness.preferences.metric.database-size"
  static let preferencesLiveSessionsCard = "harness.preferences.metric.live-sessions"
  static let reconnectButton = "harness.preferences.action.reconnect"
  static let refreshDiagnosticsButton = "harness.preferences.action.refresh-diagnostics"
  static let startDaemonButton = "harness.preferences.action.start-daemon"
  static let installLaunchAgentButton = "harness.preferences.action.install-launch-agent"
  static let removeLaunchAgentButton = "harness.preferences.action.remove-launch-agent"
  static let actionToast = "harness.action-toast"
  static let actionToastFrame = "harness.action-toast.frame"
  static let actionToastCloseButton = "harness.action-toast.close"
  static let sessionTimelinePagination = "harness.session.timeline.pagination"
  static let sessionTimelinePageSizePicker = "harness.session.timeline.pagination.page-size"
  static let sessionTimelinePaginationPrevious = "harness.session.timeline.pagination.previous"
  static let sessionTimelinePaginationNext = "harness.session.timeline.pagination.next"
  static let sessionTimelinePaginationStatus = "harness.session.timeline.pagination.status"
  static let sendSignalSheet = "harness.sheet.send-signal"
  static let sendSignalSheetCommandField = "harness.sheet.send-signal.command"
  static let sendSignalSheetMessageField = "harness.sheet.send-signal.message"
  static let sendSignalSheetMessageVoiceButton = "harness.sheet.send-signal.message.voice"
  static let sendSignalSheetActionHintField = "harness.sheet.send-signal.action-hint"
  static let sendSignalSheetCancelButton = "harness.sheet.send-signal.cancel"
  static let sendSignalSheetSubmitButton = "harness.sheet.send-signal.submit"
  static let voiceInputPopover = "harness.voice-input.popover"
  static let voiceInputTranscript = "harness.voice-input.transcript"
  static let voiceInputInsertButton = "harness.voice-input.insert"
  static let voiceInputStopButton = "harness.voice-input.stop"
  static let voiceInputFailureOverlay = "harness.voice-input.failure"
  static let voiceInputFailureMessage = "harness.voice-input.failure.message"
  static let voiceInputFailureInstructions = "harness.voice-input.failure.instructions"
  static let leaderAgentSignalTrigger = "harness.session.agent.leader-claude.signal-trigger"
  static let agentTuiButton = "harness.session.agent-tui"
  static let agentTuiSheet = "harness.sheet.agent-tui"
  static let agentTuiState = "harness.sheet.agent-tui.state"
  static let agentTuiCreateTab = "harness.sheet.agent-tui.tab.create"
  static let agentTuiRuntimePicker = "harness.sheet.agent-tui.runtime"
  static let agentTuiNameField = "harness.sheet.agent-tui.name"
  static let agentTuiPromptField = "harness.sheet.agent-tui.prompt"
  static let agentTuiLaunchPane = "harness.sheet.agent-tui.launch-pane"
  static let agentTuiSessionPane = "harness.sheet.agent-tui.session-pane"
  static let agentTuiViewport = "harness.sheet.agent-tui.viewport"
  static let agentTuiInputField = "harness.sheet.agent-tui.input"
  static let agentTuiInputModePicker = "harness.sheet.agent-tui.input-mode"
  static let agentTuiRefreshButton = "harness.sheet.agent-tui.refresh"
  static let agentTuiStartButton = "harness.sheet.agent-tui.start"
  static let agentTuiSendButton = "harness.sheet.agent-tui.send"
  static let agentTuiResizeButton = "harness.sheet.agent-tui.resize"
  static let agentTuiStopButton = "harness.sheet.agent-tui.stop"
  static let agentTuiRevealTranscriptButton = "harness.sheet.agent-tui.transcript"
  static let agentTuiRecoveryBanner = "harness.sheet.agent-tui.recovery-banner"
  static let agentTuiEnableBridgeButton = "harness.sheet.agent-tui.enable-bridge"
  static let agentTuiCopyCommandButton = "harness.sheet.agent-tui.copy-command"
  static let agentTuiBackToCreateButton = "harness.sheet.agent-tui.back-to-create"
  static let agentTuiWrapToggle = "harness.sheet.agent-tui.wrap-toggle"
  static let codexFlowButton = "harness.session.codex-flow"
  static let codexFlowWIPBadge = "harness.session.codex-flow.wip"
  static let codexFlowSheet = "harness.sheet.codex-flow"
  static let codexFlowPromptField = "harness.sheet.codex-flow.prompt"
  static let codexFlowPromptVoiceButton = "harness.sheet.codex-flow.prompt.voice"
  static let codexFlowContextField = "harness.sheet.codex-flow.context"
  static let codexFlowContextVoiceButton = "harness.sheet.codex-flow.context.voice"
  static let codexFlowModePicker = "harness.sheet.codex-flow.mode"
  static let codexFlowCancelButton = "harness.sheet.codex-flow.cancel"
  static let codexFlowSubmitButton = "harness.sheet.codex-flow.submit"
  static let codexFlowSteerButton = "harness.sheet.codex-flow.steer"
  static let codexFlowInterruptButton = "harness.sheet.codex-flow.interrupt"
  static let codexFlowRecoveryBanner = "harness.sheet.codex-flow.recovery-banner"
  static let codexFlowEnableBridgeButton = "harness.sheet.codex-flow.enable-bridge"
  static let codexFlowCopyCommandButton = "harness.sheet.codex-flow.copy-command"

  static func sessionTimelinePaginationPageButton(_ pageNumber: Int) -> String {
    "harness.session.timeline.pagination.page.\(pageNumber)"
  }

  static func projectHeader(_ projectID: String) -> String {
    "harness.sidebar.project-header.\(slug(projectID))"
  }

  static func worktreeHeader(_ checkoutID: String) -> String {
    "harness.sidebar.worktree-header.\(slug(checkoutID))"
  }

  static func preferencesBackgroundTile(_ key: String) -> String {
    "harness.preferences.background.\(slug(key))"
  }

  static func sidebarSortSegment(_ order: String) -> String {
    "harness.sidebar.sort.\(slug(order))"
  }

  static func sidebarFocusChip(_ filter: String) -> String {
    "harness.sidebar.focus-chip.\(slug(filter))"
  }

  static let leaderAgentTuiMarker = "harness.session.agent.leader-claude.tui-marker"
  static let workerAgentTuiMarker = "harness.session.agent.worker-codex.tui-marker"

  static func sessionAgentTuiMarker(_ agentID: String) -> String {
    "harness.session.agent.\(slug(agentID)).tui-marker"
  }

  static func sessionAgentTaskDropFeedback(_ agentID: String) -> String {
    "harness.session.agent.\(slug(agentID)).task-drop-feedback"
  }

  static func agentTuiTab(_ tuiID: String) -> String {
    "harness.sheet.agent-tui.tab.\(slug(tuiID))"
  }

  private static func slug(_ value: String) -> String {
    let lowercased = value.lowercased()
    return
      lowercased
      .replacing(" ", with: "-")
      .replacing("_", with: "-")
      .replacing(":", with: "-")
      .replacing("/", with: "-")
      .replacing(".", with: "")
  }
}
