[security]
# non-"admin" password skips the change password prompt on first login
admin_user = admin
admin_password = harness

[news]
# disables "Latest from the blog" panel on home page
news_feed_enabled = false

[dashboards]
# sets system-overview as the default home dashboard (skips welcome page)
default_home_dashboard_path = /var/lib/grafana/dashboards/system-overview.json

[unified_alerting]
enabled = true

[alerting]
enabled = false
