extension HarnessMonitorAccessibility {
  public static let createTaskSheet = "harness.action.create-task.sheet"
  public static let createTaskSheetDismiss = "harness.action.create-task.dismiss"
  public static let createTaskTitleField = "harness.action.create-task.title-field"
  public static let createTaskButton = "harness.action.create-task.submit"
  public static let sessionAgentCreateOpenButton = "harness.session.agents.create-agent.open"
  public static let sessionTaskCreateOpenButton = "harness.session.tasks.create-task.open"

  public static let taskActionsSheet = "harness.action.task-actions.sheet"
  public static let taskActionsSheetDismiss = "harness.action.task-actions.dismiss"
  public static let assignTaskButton = "harness.action.task.assign"
  public static let updateTaskQueuePolicyButton = "harness.action.task.update-queue-policy"
  public static let updateTaskStatusButton = "harness.action.task.update-status"
  public static let checkpointTaskButton = "harness.action.task.checkpoint"
  public static let submitTaskForReviewButton = "harness.action.task.submit-for-review"
  public static let claimTaskReviewButton = "harness.action.task.claim-review"
  public static let submitTaskReviewButton = "harness.action.task.submit-review"
  public static let respondTaskReviewButton = "harness.action.task.respond-review"
  public static let arbitrateTaskButton = "harness.action.task.arbitrate"
  public static let manageTaskOpenButton = "harness.session.task.manage-open"

  public static let leaderTransferSheet = "harness.action.leader-transfer.sheet"
  public static let leaderTransferSheetDismiss = "harness.action.leader-transfer.dismiss"
  public static let leaderTransferOpenButton = "harness.session.header.leader-transfer.open"
  public static let leaderTransferSection = "harness.action.leader-transfer.section"
  public static let leaderTransferPicker = "harness.action.leader-transfer.picker"
}
