use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use super::model::PlannedOutput;

/// Managed roots that also receive a `CLAUDE.md` (Claude Code auto-loads it).
const CLAUDE_MD_ROOTS: &[&str] = &[".claude/skills", ".claude/plugins"];

const GUIDE_TEMPLATE: &str = "\
This directory is auto-generated by `harness setup agents generate`.

Sources:
- Canonical cross-runtime skills: `agents/skills/`
- Canonical cross-runtime plugins: `agents/plugins/`
- Claude-only local skills: `local-skills/claude/` (symlinked into `.claude/skills/`)

Implementation: `src/agents/assets/render_*.rs`

Do not edit files in this directory directly — edits will be overwritten on the next
`harness setup agents generate` run.
";

/// Add guide files (`AGENTS.md` and, for Claude roots, `CLAUDE.md`) to every
/// managed root present in `outputs`.  Entries are merged into existing
/// `PlannedOutput` values so that file maps from other renderers are preserved.
pub(super) fn render_guides(
    repo_root: &Path,
    managed_roots: &[&str],
    outputs: &mut BTreeMap<PathBuf, PlannedOutput>,
) {
    for &root_rel in managed_roots {
        let root = repo_root.join(root_rel);
        let entry = outputs
            .entry(root.clone())
            .or_insert_with(|| PlannedOutput {
                managed_root: root.clone(),
                files: BTreeMap::new(),
                symlinks: BTreeMap::new(),
            });
        entry
            .files
            .insert(root.join("AGENTS.md"), GUIDE_TEMPLATE.to_owned());
        if CLAUDE_MD_ROOTS.contains(&root_rel) {
            entry
                .files
                .insert(root.join("CLAUDE.md"), GUIDE_TEMPLATE.to_owned());
        }
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::super::model::MANAGED_ROOTS;
    use super::*;

    #[test]
    fn every_managed_root_gets_agents_md() {
        let repo = PathBuf::from("/repo");
        let mut outputs = BTreeMap::new();
        render_guides(&repo, MANAGED_ROOTS, &mut outputs);

        for root_rel in MANAGED_ROOTS {
            let root = repo.join(root_rel);
            let output = outputs.get(&root).expect("output entry for root");
            assert!(
                output.files.contains_key(&root.join("AGENTS.md")),
                "missing AGENTS.md for {root_rel}"
            );
        }
    }

    #[test]
    fn claude_roots_also_get_claude_md() {
        let repo = PathBuf::from("/repo");
        let mut outputs = BTreeMap::new();
        render_guides(&repo, MANAGED_ROOTS, &mut outputs);

        for root_rel in CLAUDE_MD_ROOTS {
            let root = repo.join(root_rel);
            let output = outputs.get(&root).expect("output entry for claude root");
            assert!(
                output.files.contains_key(&root.join("CLAUDE.md")),
                "missing CLAUDE.md for {root_rel}"
            );
        }
    }

    #[test]
    fn non_claude_roots_do_not_get_claude_md() {
        let repo = PathBuf::from("/repo");
        let mut outputs = BTreeMap::new();
        render_guides(&repo, MANAGED_ROOTS, &mut outputs);

        for root_rel in MANAGED_ROOTS {
            if CLAUDE_MD_ROOTS.contains(root_rel) {
                continue;
            }
            let root = repo.join(root_rel);
            let output = outputs.get(&root).expect("output entry");
            assert!(
                !output.files.contains_key(&root.join("CLAUDE.md")),
                "unexpected CLAUDE.md for {root_rel}"
            );
        }
    }

    #[test]
    fn guides_merge_with_existing_files() {
        let repo = PathBuf::from("/repo");
        let root = repo.join(".claude/skills");
        let existing_file = root.join("some-skill/SKILL.md");
        let mut outputs = BTreeMap::new();
        outputs.insert(
            root.clone(),
            PlannedOutput {
                managed_root: root.clone(),
                files: BTreeMap::from([(existing_file.clone(), "existing".to_owned())]),
                symlinks: BTreeMap::new(),
            },
        );

        render_guides(&repo, &[".claude/skills"], &mut outputs);

        let output = outputs.get(&root).unwrap();
        assert!(
            output.files.contains_key(&existing_file),
            "existing file preserved"
        );
        assert!(
            output.files.contains_key(&root.join("AGENTS.md")),
            "AGENTS.md added"
        );
        assert!(
            output.files.contains_key(&root.join("CLAUDE.md")),
            "CLAUDE.md added"
        );
    }
}
