use std::fmt;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Stable internal identity for a classified issue family.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IssueCode {
    HookDeniedToolCall,
    HarnessCliErrorOutput,
    ToolUsageErrorOutput,
    BuildOrLintFailure,
    WorkflowStateErrorOutput,
    PodContainerRuntimeFailure,
    AuthFlowTriggered,
    DirectKubectlValidateUsage,
    ShellAliasInterference,
    PayloadWrappedInJsonTags,
    PythonTracebackOutput,
    SuiteDeviationDetected,
    ReleaseKumactlBinaryUsed,
    PythonUsedInBashOutput,
    CorporateClusterContextDetected,
    HarnessHookCodeTriggered,
    ManifestRuntimeFailure,
    HarnessCreateCommandFailure,
    NonZeroExitCode,
    SubagentPermissionFailure,
    SubagentManualRecovery,
    ManualPayloadRecovery,
    MissingClaudeSessionId,
    EmptyKubeconfig,
    IncompleteWriterOutput,
    UserFrustrationDetected,
    OldSkillNameUsedInCommand,
    InvalidHarnessSubcommandUsed,
    PythonUsedInBashToolUse,
    UnverifiedRecursiveRemove,
    RawClusterMakeTargetUsed,
    UnauthorizedGitCommitDuringRun,
    ManualKubeconfigConstruction,
    ManualExportConstruction,
    ManualEnvPrefixConstruction,
    ManifestFixPromptShown,
    ValidatorInstallPromptShown,
    RuntimeDeviationPromptShown,
    WrongSkillCrossReference,
    FileEditChurn,
    ShortSkillNameInSkillFile,
    AbsoluteManifestPathUsed,
    DirectManagedFileWrite,
    ManifestCreatedDuringRun,
    DirectTaskOutputFileRead,
    HarnessInfrastructureMisconfiguration,
    MissingConnectionOrEnvVar,
    SleepPrefixBeforeHarnessCommand,
    JqErrorInCommandOutput,
    CloseoutVerdictPending,
    RunnerStateEventNotSupported,
    RunnerStateMachineStale,
    UncommittedSourceCodeEdit,
    ResourceNotCleanedUpBeforeGroupEnd,
    RepeatedKubectlQueryForSameResource,
    GroupReportedWithoutCapture,
    VerificationOutputTruncated,
}

impl fmt::Display for IssueCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::HookDeniedToolCall => "hook_denied_tool_call",
            Self::HarnessCliErrorOutput => "harness_cli_error_output",
            Self::ToolUsageErrorOutput => "tool_usage_error_output",
            Self::BuildOrLintFailure => "build_or_lint_failure",
            Self::WorkflowStateErrorOutput => "workflow_state_error_output",
            Self::PodContainerRuntimeFailure => "pod_container_runtime_failure",
            Self::AuthFlowTriggered => "auth_flow_triggered",
            Self::DirectKubectlValidateUsage => "direct_kubectl_validate_usage",
            Self::ShellAliasInterference => "shell_alias_interference",
            Self::PayloadWrappedInJsonTags => "payload_wrapped_in_json_tags",
            Self::PythonTracebackOutput => "python_traceback_output",
            Self::SuiteDeviationDetected => "suite_deviation_detected",
            Self::ReleaseKumactlBinaryUsed => "release_kumactl_binary_used",
            Self::PythonUsedInBashOutput => "python_used_in_bash_output",
            Self::CorporateClusterContextDetected => "corporate_cluster_context_detected",
            Self::HarnessHookCodeTriggered => "harness_hook_code_triggered",
            Self::ManifestRuntimeFailure => "manifest_runtime_failure",
            Self::HarnessCreateCommandFailure => "harness_create_command_failure",
            Self::NonZeroExitCode => "non_zero_exit_code",
            Self::SubagentPermissionFailure => "subagent_permission_failure",
            Self::SubagentManualRecovery => "subagent_manual_recovery",
            Self::ManualPayloadRecovery => "manual_payload_recovery",
            Self::MissingClaudeSessionId => "missing_claude_session_id",
            Self::EmptyKubeconfig => "empty_kubeconfig",
            Self::IncompleteWriterOutput => "incomplete_writer_output",
            Self::UserFrustrationDetected => "user_frustration_detected",
            Self::OldSkillNameUsedInCommand => "old_skill_name_used_in_command",
            Self::InvalidHarnessSubcommandUsed => "invalid_harness_subcommand_used",
            Self::PythonUsedInBashToolUse => "python_used_in_bash_tool_use",
            Self::UnverifiedRecursiveRemove => "unverified_recursive_remove",
            Self::RawClusterMakeTargetUsed => "raw_cluster_make_target_used",
            Self::UnauthorizedGitCommitDuringRun => "unauthorized_git_commit_during_run",
            Self::ManualKubeconfigConstruction => "manual_kubeconfig_construction",
            Self::ManualExportConstruction => "manual_export_construction",
            Self::ManualEnvPrefixConstruction => "manual_env_prefix_construction",
            Self::ManifestFixPromptShown => "manifest_fix_prompt_shown",
            Self::ValidatorInstallPromptShown => "validator_install_prompt_shown",
            Self::RuntimeDeviationPromptShown => "runtime_deviation_prompt_shown",
            Self::WrongSkillCrossReference => "wrong_skill_cross_reference",
            Self::FileEditChurn => "file_edit_churn",
            Self::ShortSkillNameInSkillFile => "short_skill_name_in_skill_file",
            Self::AbsoluteManifestPathUsed => "absolute_manifest_path_used",
            Self::DirectManagedFileWrite => "direct_managed_file_write",
            Self::ManifestCreatedDuringRun => "manifest_created_during_run",
            Self::DirectTaskOutputFileRead => "direct_task_output_file_read",
            Self::HarnessInfrastructureMisconfiguration => {
                "harness_infrastructure_misconfiguration"
            }
            Self::MissingConnectionOrEnvVar => "missing_connection_or_env_var",
            Self::SleepPrefixBeforeHarnessCommand => "sleep_prefix_before_harness_command",
            Self::JqErrorInCommandOutput => "jq_error_in_command_output",
            Self::CloseoutVerdictPending => "closeout_verdict_pending",
            Self::RunnerStateEventNotSupported => "runner_state_event_not_supported",
            Self::RunnerStateMachineStale => "runner_state_machine_stale",
            Self::UncommittedSourceCodeEdit => "uncommitted_source_code_edit",
            Self::ResourceNotCleanedUpBeforeGroupEnd => "resource_not_cleaned_up_before_group_end",
            Self::RepeatedKubectlQueryForSameResource => "repeated_kubectl_query_for_same_resource",
            Self::GroupReportedWithoutCapture => "group_reported_without_capture",
            Self::VerificationOutputTruncated => "verification_output_truncated",
        };
        f.write_str(label)
    }
}

impl IssueCode {
    /// Parse from `snake_case` label.
    #[must_use]
    pub fn from_label(s: &str) -> Option<Self> {
        match s {
            "hook_denied_tool_call" => Some(Self::HookDeniedToolCall),
            "harness_cli_error_output" => Some(Self::HarnessCliErrorOutput),
            "tool_usage_error_output" => Some(Self::ToolUsageErrorOutput),
            "build_or_lint_failure" => Some(Self::BuildOrLintFailure),
            "workflow_state_error_output" => Some(Self::WorkflowStateErrorOutput),
            "pod_container_runtime_failure" => Some(Self::PodContainerRuntimeFailure),
            "auth_flow_triggered" => Some(Self::AuthFlowTriggered),
            "direct_kubectl_validate_usage" => Some(Self::DirectKubectlValidateUsage),
            "shell_alias_interference" => Some(Self::ShellAliasInterference),
            "payload_wrapped_in_json_tags" => Some(Self::PayloadWrappedInJsonTags),
            "python_traceback_output" => Some(Self::PythonTracebackOutput),
            "suite_deviation_detected" => Some(Self::SuiteDeviationDetected),
            "release_kumactl_binary_used" => Some(Self::ReleaseKumactlBinaryUsed),
            "python_used_in_bash_output" => Some(Self::PythonUsedInBashOutput),
            "corporate_cluster_context_detected" => Some(Self::CorporateClusterContextDetected),
            "harness_hook_code_triggered" => Some(Self::HarnessHookCodeTriggered),
            "manifest_runtime_failure" => Some(Self::ManifestRuntimeFailure),
            "harness_create_command_failure" => Some(Self::HarnessCreateCommandFailure),
            "non_zero_exit_code" => Some(Self::NonZeroExitCode),
            "subagent_permission_failure" => Some(Self::SubagentPermissionFailure),
            "subagent_manual_recovery" => Some(Self::SubagentManualRecovery),
            "manual_payload_recovery" => Some(Self::ManualPayloadRecovery),
            "missing_claude_session_id" => Some(Self::MissingClaudeSessionId),
            "empty_kubeconfig" => Some(Self::EmptyKubeconfig),
            "incomplete_writer_output" => Some(Self::IncompleteWriterOutput),
            "user_frustration_detected" => Some(Self::UserFrustrationDetected),
            "old_skill_name_used_in_command" => Some(Self::OldSkillNameUsedInCommand),
            "invalid_harness_subcommand_used" => Some(Self::InvalidHarnessSubcommandUsed),
            "python_used_in_bash_tool_use" => Some(Self::PythonUsedInBashToolUse),
            "unverified_recursive_remove" => Some(Self::UnverifiedRecursiveRemove),
            "raw_cluster_make_target_used" => Some(Self::RawClusterMakeTargetUsed),
            "unauthorized_git_commit_during_run" => Some(Self::UnauthorizedGitCommitDuringRun),
            "manual_kubeconfig_construction" => Some(Self::ManualKubeconfigConstruction),
            "manual_export_construction" => Some(Self::ManualExportConstruction),
            "manual_env_prefix_construction" => Some(Self::ManualEnvPrefixConstruction),
            "manifest_fix_prompt_shown" => Some(Self::ManifestFixPromptShown),
            "validator_install_prompt_shown" => Some(Self::ValidatorInstallPromptShown),
            "runtime_deviation_prompt_shown" => Some(Self::RuntimeDeviationPromptShown),
            "wrong_skill_cross_reference" => Some(Self::WrongSkillCrossReference),
            "file_edit_churn" => Some(Self::FileEditChurn),
            "short_skill_name_in_skill_file" => Some(Self::ShortSkillNameInSkillFile),
            "absolute_manifest_path_used" => Some(Self::AbsoluteManifestPathUsed),
            "direct_managed_file_write" => Some(Self::DirectManagedFileWrite),
            "manifest_created_during_run" => Some(Self::ManifestCreatedDuringRun),
            "direct_task_output_file_read" => Some(Self::DirectTaskOutputFileRead),
            "harness_infrastructure_misconfiguration" => {
                Some(Self::HarnessInfrastructureMisconfiguration)
            }
            "missing_connection_or_env_var" => Some(Self::MissingConnectionOrEnvVar),
            "sleep_prefix_before_harness_command" => Some(Self::SleepPrefixBeforeHarnessCommand),
            "jq_error_in_command_output" => Some(Self::JqErrorInCommandOutput),
            "closeout_verdict_pending" => Some(Self::CloseoutVerdictPending),
            "runner_state_event_not_supported" => Some(Self::RunnerStateEventNotSupported),
            "runner_state_machine_stale" => Some(Self::RunnerStateMachineStale),
            "uncommitted_source_code_edit" => Some(Self::UncommittedSourceCodeEdit),
            "resource_not_cleaned_up_before_group_end" => {
                Some(Self::ResourceNotCleanedUpBeforeGroupEnd)
            }
            "repeated_kubectl_query_for_same_resource" => {
                Some(Self::RepeatedKubectlQueryForSameResource)
            }
            "group_reported_without_capture" => Some(Self::GroupReportedWithoutCapture),
            "verification_output_truncated" => Some(Self::VerificationOutputTruncated),
            _ => None,
        }
    }

    /// All code variants for enumeration.
    pub const ALL: &'static [Self] = &[
        Self::HookDeniedToolCall,
        Self::HarnessCliErrorOutput,
        Self::ToolUsageErrorOutput,
        Self::BuildOrLintFailure,
        Self::WorkflowStateErrorOutput,
        Self::PodContainerRuntimeFailure,
        Self::AuthFlowTriggered,
        Self::DirectKubectlValidateUsage,
        Self::ShellAliasInterference,
        Self::PayloadWrappedInJsonTags,
        Self::PythonTracebackOutput,
        Self::SuiteDeviationDetected,
        Self::ReleaseKumactlBinaryUsed,
        Self::PythonUsedInBashOutput,
        Self::CorporateClusterContextDetected,
        Self::HarnessHookCodeTriggered,
        Self::ManifestRuntimeFailure,
        Self::HarnessCreateCommandFailure,
        Self::NonZeroExitCode,
        Self::SubagentPermissionFailure,
        Self::SubagentManualRecovery,
        Self::ManualPayloadRecovery,
        Self::MissingClaudeSessionId,
        Self::EmptyKubeconfig,
        Self::IncompleteWriterOutput,
        Self::UserFrustrationDetected,
        Self::OldSkillNameUsedInCommand,
        Self::InvalidHarnessSubcommandUsed,
        Self::PythonUsedInBashToolUse,
        Self::UnverifiedRecursiveRemove,
        Self::RawClusterMakeTargetUsed,
        Self::UnauthorizedGitCommitDuringRun,
        Self::ManualKubeconfigConstruction,
        Self::ManualExportConstruction,
        Self::ManualEnvPrefixConstruction,
        Self::ManifestFixPromptShown,
        Self::ValidatorInstallPromptShown,
        Self::RuntimeDeviationPromptShown,
        Self::WrongSkillCrossReference,
        Self::FileEditChurn,
        Self::ShortSkillNameInSkillFile,
        Self::AbsoluteManifestPathUsed,
        Self::DirectManagedFileWrite,
        Self::ManifestCreatedDuringRun,
        Self::DirectTaskOutputFileRead,
        Self::HarnessInfrastructureMisconfiguration,
        Self::MissingConnectionOrEnvVar,
        Self::SleepPrefixBeforeHarnessCommand,
        Self::JqErrorInCommandOutput,
        Self::CloseoutVerdictPending,
        Self::RunnerStateEventNotSupported,
        Self::RunnerStateMachineStale,
        Self::UncommittedSourceCodeEdit,
        Self::ResourceNotCleanedUpBeforeGroupEnd,
        Self::RepeatedKubectlQueryForSameResource,
        Self::GroupReportedWithoutCapture,
        Self::VerificationOutputTruncated,
    ];
}

/// Compute a stable 12-char hex issue identity from code + fingerprint.
#[must_use]
pub fn compute_issue_id(code: IssueCode, fingerprint: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(code.to_string().as_bytes());
    hasher.update(b"\0");
    hasher.update(fingerprint.as_bytes());
    let digest = hasher.finalize();
    hex::encode(&digest[..6])
}
