use super::*;

// Each `_part_N` helper below is a slice of the same literal table, split
// purely to keep every function under the repo's line cap; there is no
// per-part meaning; `expected_task_board_ws_parity` below is the real API.
fn task_board_ws_parity_part_1() -> Vec<(HttpRouteMethod, &'static str, &'static str, bool)> {
    vec![
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_CAPABILITIES,
            ws_methods::TASK_BOARD_CAPABILITIES,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_ITEMS,
            ws_methods::TASK_BOARD_CREATE,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ITEMS,
            ws_methods::TASK_BOARD_LIST,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ITEM,
            ws_methods::TASK_BOARD_GET,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ITEM_REVIEW_REPORT,
            ws_methods::TASK_BOARD_REVIEW_REPORT_GET,
            true,
        ),
        (
            HttpRouteMethod::Put,
            http_paths::TASK_BOARD_ITEM,
            ws_methods::TASK_BOARD_UPDATE,
            true,
        ),
        (
            HttpRouteMethod::Delete,
            http_paths::TASK_BOARD_ITEM,
            ws_methods::TASK_BOARD_DELETE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_PLAN_BEGIN,
            ws_methods::TASK_BOARD_PLAN_BEGIN,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_PLAN_SUBMIT,
            ws_methods::TASK_BOARD_PLAN_SUBMIT,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_PLAN_APPROVE,
            ws_methods::TASK_BOARD_PLAN_APPROVE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_PLAN_REVOKE,
            ws_methods::TASK_BOARD_PLAN_REVOKE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_SYNC,
            ws_methods::TASK_BOARD_SYNC,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_DISPATCH,
            ws_methods::TASK_BOARD_DISPATCH,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_DISPATCH_DELIVER,
            ws_methods::TASK_BOARD_DISPATCH_DELIVER,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_DISPATCH_PICK,
            ws_methods::TASK_BOARD_DISPATCH_PICK,
            true,
        ),
    ]
}

fn task_board_ws_parity_part_2() -> Vec<(HttpRouteMethod, &'static str, &'static str, bool)> {
    vec![
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_EVALUATE,
            ws_methods::TASK_BOARD_EVALUATE,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_AUDIT,
            ws_methods::TASK_BOARD_AUDIT,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_PROJECTS,
            ws_methods::TASK_BOARD_PROJECTS,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_PROJECTS_UPDATE,
            ws_methods::TASK_BOARD_PROJECTS_UPDATE,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_MACHINES,
            ws_methods::TASK_BOARD_MACHINES,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_HOST_LOCAL,
            ws_methods::TASK_BOARD_HOST_LOCAL,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_HOST_LIST,
            ws_methods::TASK_BOARD_HOST_LIST,
            true,
        ),
        (
            HttpRouteMethod::Put,
            http_paths::TASK_BOARD_HOST_SET_PROJECT_TYPES,
            ws_methods::TASK_BOARD_HOST_SET_PROJECT_TYPES,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ORCHESTRATOR_STATUS,
            ws_methods::TASK_BOARD_ORCHESTRATOR_STATUS,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_ORCHESTRATOR_START,
            ws_methods::TASK_BOARD_ORCHESTRATOR_START,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_ORCHESTRATOR_STOP,
            ws_methods::TASK_BOARD_ORCHESTRATOR_STOP,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_ORCHESTRATOR_RUN_ONCE,
            ws_methods::TASK_BOARD_ORCHESTRATOR_RUN_ONCE,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ORCHESTRATOR_SETTINGS,
            ws_methods::TASK_BOARD_ORCHESTRATOR_SETTINGS_GET,
            true,
        ),
        (
            HttpRouteMethod::Put,
            http_paths::TASK_BOARD_ORCHESTRATOR_SETTINGS,
            ws_methods::TASK_BOARD_ORCHESTRATOR_SETTINGS_UPDATE,
            true,
        ),
    ]
}

fn task_board_ws_parity_part_3() -> Vec<(HttpRouteMethod, &'static str, &'static str, bool)> {
    vec![
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ORCHESTRATOR_RUNTIME_CONFIG,
            ws_methods::TASK_BOARD_ORCHESTRATOR_RUNTIME_CONFIG_GET,
            true,
        ),
        (
            HttpRouteMethod::Put,
            http_paths::TASK_BOARD_ORCHESTRATOR_RUNTIME_CONFIG,
            ws_methods::TASK_BOARD_ORCHESTRATOR_RUNTIME_CONFIG_UPDATE,
            true,
        ),
        (
            HttpRouteMethod::Put,
            http_paths::TASK_BOARD_ORCHESTRATOR_GITHUB_TOKENS,
            ws_methods::TASK_BOARD_ORCHESTRATOR_GITHUB_TOKENS_SYNC,
            true,
        ),
        (
            HttpRouteMethod::Put,
            http_paths::TASK_BOARD_ORCHESTRATOR_OPENROUTER_TOKEN,
            ws_methods::TASK_BOARD_ORCHESTRATOR_OPENROUTER_TOKEN_SYNC,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_GIT_IDENTITY_DEFAULTS,
            ws_methods::TASK_BOARD_GIT_IDENTITY_DEFAULTS,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_GIT_SIGNING_VERIFY,
            ws_methods::TASK_BOARD_GIT_SIGNING_VERIFY,
            true,
        ),
        (
            HttpRouteMethod::Put,
            http_paths::TASK_BOARD_GIT_RUNTIME_KEY_MATERIAL,
            ws_methods::TASK_BOARD_GIT_RUNTIME_KEY_MATERIAL_SYNC,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_GIT_RUNTIME_SECRET_HANDOFF_PREPARE,
            ws_methods::TASK_BOARD_GIT_RUNTIME_SECRET_HANDOFF_PREPARE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_GIT_RUNTIME_SECRET_HANDOFF_ACK,
            ws_methods::TASK_BOARD_GIT_RUNTIME_SECRET_HANDOFF_ACK,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::POLICY_CANVASES,
            ws_methods::POLICY_CANVAS_WORKSPACE_GET,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_CANVASES_CREATE,
            ws_methods::POLICY_CANVAS_CREATE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_CANVASES_DUPLICATE,
            ws_methods::POLICY_CANVAS_DUPLICATE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_CANVASES_RENAME,
            ws_methods::POLICY_CANVAS_RENAME,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_CANVASES_ACTIVE,
            ws_methods::POLICY_CANVAS_SET_ACTIVE,
            true,
        ),
    ]
}

#[path = "task_board_ws_parity_expected_more.rs"]
mod more;

/// The full expected `(method, path, ws_method, swift_client_exposed)` table
/// for `task_board_routes_have_complete_ws_parity`, split into its own file
/// (and `more`, a further split of the same table) purely to keep
/// `task_board.rs` under the repo's line cap -- this is pure literal data,
/// not logic.
pub(super) fn expected_task_board_ws_parity()
-> Vec<(HttpRouteMethod, &'static str, &'static str, bool)> {
    let mut expected = Vec::new();
    expected.extend(task_board_ws_parity_part_1());
    expected.extend(task_board_ws_parity_part_2());
    expected.extend(task_board_ws_parity_part_3());
    expected.extend(more::task_board_ws_parity_part_4());
    expected.extend(more::task_board_ws_parity_part_5());
    expected.extend(more::task_board_ws_parity_part_6());
    expected
}
