use super::*;

pub(super) fn task_board_ws_parity_part_4()
-> Vec<(HttpRouteMethod, &'static str, &'static str, bool)> {
    vec![
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_CANVASES_DELETE,
            ws_methods::POLICY_CANVAS_DELETE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_CANVASES_GLOBAL_ENFORCEMENT,
            ws_methods::POLICY_CANVAS_SET_GLOBAL_ENFORCEMENT,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_CANVASES_SPAWN_REQUIRES_LIVE_POLICY,
            ws_methods::POLICY_CANVAS_SET_SPAWN_REQUIRES_LIVE_POLICY,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_CANVASES_SPAWN_KILL_SWITCH,
            ws_methods::POLICY_CANVAS_SET_SPAWN_KILL_SWITCH,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::POLICY_APPROVAL_GRANTS,
            ws_methods::POLICY_APPROVAL_GRANTS_LIST,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_APPROVAL_GRANT_RESOLVE,
            ws_methods::POLICY_APPROVAL_GRANT_RESOLVE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_APPROVAL_GRANT_REVOKE,
            ws_methods::POLICY_APPROVAL_GRANT_REVOKE,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::POLICY_PIPELINE,
            ws_methods::POLICY_PIPELINE_GET,
            true,
        ),
        (
            HttpRouteMethod::Put,
            http_paths::POLICY_PIPELINE,
            ws_methods::POLICY_PIPELINE_SAVE_DRAFT,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_SIMULATE,
            ws_methods::POLICY_PIPELINE_SIMULATE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_PROMOTE,
            ws_methods::POLICY_PIPELINE_PROMOTE,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::POLICY_AUDIT,
            ws_methods::POLICY_PIPELINE_AUDIT,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_CANVAS_EXPORT,
            ws_methods::POLICY_CANVAS_EXPORT,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_CANVAS_IMPORT,
            ws_methods::POLICY_CANVAS_IMPORT,
            true,
        ),
    ]
}

pub(super) fn task_board_ws_parity_part_5()
-> Vec<(HttpRouteMethod, &'static str, &'static str, bool)> {
    vec![
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_SCENARIOS_CREATE,
            ws_methods::POLICY_SCENARIO_CREATE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_SCENARIOS_UPDATE,
            ws_methods::POLICY_SCENARIO_UPDATE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_SCENARIOS_DELETE,
            ws_methods::POLICY_SCENARIO_DELETE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_SCENARIOS_RESET,
            ws_methods::POLICY_SCENARIO_RESET,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_MAKE_LIVE,
            ws_methods::POLICY_PIPELINE_MAKE_LIVE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_GO_LIVE_DIFF,
            ws_methods::POLICY_PIPELINE_GO_LIVE_DIFF,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::POLICY_REPLAY,
            ws_methods::POLICY_PIPELINE_REPLAY,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_WORKING_COPIES,
            ws_methods::TASK_BOARD_WORKING_COPIES_LIST,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_WORKING_COPIES_OBTAIN,
            ws_methods::TASK_BOARD_WORKING_COPIES_OBTAIN,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_WORKING_COPIES_DELETE,
            ws_methods::TASK_BOARD_WORKING_COPIES_DELETE,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ITEM_POSITION,
            ws_methods::TASK_BOARD_POSITION_GET,
            true,
        ),
        (
            HttpRouteMethod::Put,
            http_paths::TASK_BOARD_ITEM_POSITION,
            ws_methods::TASK_BOARD_POSITION_SET,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_ITEM_POSITION_RESET,
            ws_methods::TASK_BOARD_POSITION_RESET,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ITEM_TRIAGE,
            ws_methods::TASK_BOARD_TRIAGE_GET,
            true,
        ),
    ]
}

pub(super) fn task_board_ws_parity_part_6()
-> Vec<(HttpRouteMethod, &'static str, &'static str, bool)> {
    vec![
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ITEM_TRIAGE_HISTORY,
            ws_methods::TASK_BOARD_TRIAGE_HISTORY,
            true,
        ),
        (
            HttpRouteMethod::Put,
            http_paths::TASK_BOARD_ITEM_TRIAGE_OVERRIDE,
            ws_methods::TASK_BOARD_TRIAGE_OVERRIDE_SET,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_ITEM_TRIAGE_OVERRIDE_CLEAR,
            ws_methods::TASK_BOARD_TRIAGE_OVERRIDE_CLEAR,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_TRIAGE_RULES_DRAFT,
            ws_methods::TASK_BOARD_TRIAGE_RULES_DRAFT_GET,
            true,
        ),
        (
            HttpRouteMethod::Put,
            http_paths::TASK_BOARD_TRIAGE_RULES_DRAFT,
            ws_methods::TASK_BOARD_TRIAGE_RULES_DRAFT_SAVE,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_TRIAGE_RULES_PREVIEW,
            ws_methods::TASK_BOARD_TRIAGE_RULES_PREVIEW,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_TRIAGE_RULES_ACTIVATE,
            ws_methods::TASK_BOARD_TRIAGE_RULES_ACTIVATE,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_TRIAGE_RULES_REVISIONS,
            ws_methods::TASK_BOARD_TRIAGE_RULES_REVISIONS,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_TRIAGE_RULES_AUDIT,
            ws_methods::TASK_BOARD_TRIAGE_RULES_AUDIT,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ORCHESTRATOR_RUNS,
            ws_methods::TASK_BOARD_ORCHESTRATOR_RUNS,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ORCHESTRATOR_RUN_DETAIL,
            ws_methods::TASK_BOARD_ORCHESTRATOR_RUN_DETAIL,
            true,
        ),
        (
            HttpRouteMethod::Get,
            http_paths::TASK_BOARD_ORCHESTRATOR_METRICS,
            ws_methods::TASK_BOARD_ORCHESTRATOR_METRICS,
            true,
        ),
        (
            HttpRouteMethod::Post,
            http_paths::TASK_BOARD_ORCHESTRATOR_FORCE_CANCEL,
            ws_methods::TASK_BOARD_ORCHESTRATOR_FORCE_CANCEL,
            true,
        ),
    ]
}
