import Testing

@testable import HarnessMonitorKit
@testable import HarnessMonitorUIPreviewable

@Suite("Agent name prefill view-model contract")
@MainActor
struct AgentNamePrefillContractTests {
  @Test("Empty name gets prefilled on appear")
  func emptyNamePrefills() {
    let viewModel = WorkspaceWindowView.ViewModel(selection: .create)
    viewModel.selectedLaunchSelection = .tui(.codex)
    viewModel.name = ""

    WorkspaceWindowCreatePane.prefillAgentNameIfEligible(viewModel: viewModel, taken: [])

    #expect(!viewModel.name.isEmpty)
    #expect(viewModel.lastAutoGeneratedName == viewModel.name)
  }

  @Test("User-typed name is preserved across provider change")
  func userTypedNamePreserved() {
    let viewModel = WorkspaceWindowView.ViewModel(selection: .create)
    viewModel.selectedLaunchSelection = .tui(.codex)
    viewModel.name = "My Custom Agent"
    viewModel.lastAutoGeneratedName = nil

    WorkspaceWindowCreatePane.prefillAgentNameIfEligible(viewModel: viewModel, taken: [])

    #expect(viewModel.name == "My Custom Agent")
  }

  @Test("Auto-generated name regenerates on provider change")
  func autoGeneratedNameRegenerates() {
    let viewModel = WorkspaceWindowView.ViewModel(selection: .create)
    viewModel.selectedLaunchSelection = .tui(.codex)
    WorkspaceWindowCreatePane.prefillAgentNameIfEligible(viewModel: viewModel, taken: [])
    let firstName = viewModel.name
    #expect(!firstName.isEmpty)
    #expect(AgentNameGenerator.validate(firstName, runtime: .codex))

    viewModel.selectedLaunchSelection = .tui(.gemini)
    WorkspaceWindowCreatePane.prefillAgentNameIfEligible(viewModel: viewModel, taken: [])

    #expect(AgentNameGenerator.validate(viewModel.name, runtime: .gemini))
  }

  @Test("Regenerate replaces current name and updates flag")
  func regenerateReplacesCurrent() {
    let viewModel = WorkspaceWindowView.ViewModel(selection: .create)
    viewModel.selectedLaunchSelection = .tui(.codex)
    viewModel.name = "Some Name"
    viewModel.lastAutoGeneratedName = nil

    WorkspaceWindowCreatePane.regenerateAgentName(viewModel: viewModel, taken: [])

    #expect(viewModel.name != "Some Name")
    #expect(viewModel.lastAutoGeneratedName == viewModel.name)
    #expect(AgentNameGenerator.validate(viewModel.name, runtime: .codex))
  }

  @Test("Validation warning surfaces empty and clash states")
  func validationWarning() {
    let viewModel = WorkspaceWindowView.ViewModel(selection: .create)
    viewModel.selectedLaunchSelection = .tui(.codex)

    viewModel.name = ""
    #expect(
      WorkspaceWindowCreatePane.agentNameValidationWarning(viewModel: viewModel, taken: [])
        == "Display name is required."
    )

    viewModel.name = "Cassandra Maxwell"
    #expect(
      WorkspaceWindowCreatePane.agentNameValidationWarning(
        viewModel: viewModel,
        taken: ["cassandra maxwell"]
      ) == "An agent with this name already exists in the session."
    )

    viewModel.name = "Cassandra Maxwell"
    #expect(
      WorkspaceWindowCreatePane.agentNameValidationWarning(
        viewModel: viewModel,
        taken: ["Other Agent"]
      ) == nil
    )
  }
}
