[package]
name = "harness-daemon-discovery"
version = "55.0.1"
edition = "2024"
rust-version = "1.95"
publish = false

[dependencies]
harness-daemon-client = { path = "../harness-daemon-client", version = "55.0.1" }
harness-daemon-root = { path = "../harness-daemon-root", version = "55.0.1" }
harness-workspace = { path = "../harness-workspace", version = "55.0.1" }

[dev-dependencies]
fs2 = "0.4.3"
temp-env = { version = "=0.3.6", features = ["async_closure"] }
tempfile = "3.27.0"

[lints.clippy]
pedantic = { level = "deny", priority = 1 }

[lints.rust]
unused = { level = "deny", priority = 1 }
