nextest-version = "0.9.140"

[profile.default]
test-threads = "num-cpus"
fail-fast = false
status-level = "fail"
final-status-level = "fail"

[profile.rust-timing]
test-threads = "num-cpus"
retries = 0
fail-fast = false
status-level = "slow"
final-status-level = "slow"
success-output = "never"
slow-timeout = "100ms"

[profile.rust-timing.junit]
path = "junit.xml"
report-name = "harness-rust-timing"
store-success-output = false
store-failure-output = true
