//! `OpenAPI` 3.1 document generation for the daemon HTTP API.
//!
//! The document is assembled from `#[utoipa::path]` annotations on the daemon
//! handlers plus `#[derive(utoipa::ToSchema)]` on their request and response
//! types. Per-domain [`utoipa::OpenApi`] aggregators are merged into a single
//! document; `x-websocket-method` extensions and generator provenance are
//! injected at the JSON layer from the authoritative [`HTTP_API_CONTRACT`].
//!
//! This module compiles only under the `openapi` feature. The checked-in
//! artifact `docs/api/openapi.json` is regenerated by `tools/openapi-codegen`
//! (`mise run openapi:generate`) and drift-checked by `mise run openapi:check`.

use serde::{Deserialize, Serialize};
use utoipa::OpenApi;

use crate::daemon::protocol::{HTTP_API_CONTRACT, HttpRouteMethod};

/// Error envelope returned by daemon handlers on failure.
///
/// Mirrors the dominant shape produced by `error_status_and_body`
/// (`{"error": {"code", "message", "details"}}`). A few endpoints emit
/// alternate ad-hoc error shapes for specific conditions; those are noted in
/// the relevant operation descriptions.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct DaemonErrorBody {
    pub error: DaemonErrorDetail,
}

/// Structured error detail carried by [`DaemonErrorBody`].
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct DaemonErrorDetail {
    /// Stable machine-readable error code (for example `SESSION_SCOPE_DENIED`).
    pub code: String,
    /// Human-readable error message.
    pub message: String,
    /// Optional additional context lines.
    #[serde(default)]
    pub details: Vec<String>,
}

/// Ad-hoc error body emitted by a few session endpoints that predate the
/// standard [`DaemonErrorBody`] envelope. It always carries a short string
/// `error` tag or message; some responses add variant-specific fields, which
/// the owning operation documents. The schema leaves additional properties
/// open so those variant fields validate.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct SessionAdHocError {
    /// Error tag or message, for example `already-attached` or
    /// `session not found`.
    pub error: String,
}

#[derive(utoipa::OpenApi)]
#[openapi(
    info(
        title = "Harness daemon API",
        description = "REST API served by the Harness daemon (harness-daemon). The API is dual-transport: most endpoints mirror a WebSocket JSON-RPC method, recorded per operation as the `x-websocket-method` extension. Generated from annotated handlers - do not edit docs/api/openapi.json by hand; regenerate with `mise run openapi:generate`.",
        license(name = "MIT")
    ),
    components(schemas(DaemonErrorBody, DaemonErrorDetail))
)]
struct HarnessDaemonApi;

#[derive(utoipa::OpenApi)]
#[openapi(paths(
    super::core::get_health,
    super::core::get_ready,
    super::core::post_stop_daemon,
    super::core::get_log_level,
    super::core::put_log_level,
    super::core::post_daemon_telemetry,
    super::core::get_github_status,
    super::core::get_projects,
    super::core::get_runtime_session_resolution,
))]
struct CoreApi;

#[derive(utoipa::OpenApi)]
#[openapi(paths(
    super::sessions::get_sessions,
    super::sessions_mutations::post_session_start,
    super::sessions_adopt::post_session_adopt,
    super::sessions::get_session,
    super::sessions_mutations::delete_session,
    super::sessions::get_timeline,
    super::sessions_mutations::post_session_join,
    super::runtime_session::post_runtime_session,
    super::sessions_mutations::post_session_title,
    super::sessions_mutations::post_end_session,
    super::sessions_mutations::post_session_archive,
    super::sessions_mutations::post_leave_session,
    super::sessions_mutations::post_observe_session,
))]
struct SessionsApi;

/// Build the typed `OpenAPI` document from every domain aggregator.
///
/// Aggregators merge in registration order; component schemas deduplicate by
/// name. As new route domains are annotated in later slices, add their
/// aggregator's `merge` call here.
#[must_use]
pub fn openapi_document() -> utoipa::openapi::OpenApi {
    let mut doc = HarnessDaemonApi::openapi();
    doc.merge(CoreApi::openapi());
    doc.merge(SessionsApi::openapi());
    env!("CARGO_PKG_VERSION").clone_into(&mut doc.info.version);
    doc
}

/// Render the `OpenAPI` document as a canonical JSON value with
/// `x-websocket-method` extensions and generator provenance injected.
///
/// # Panics
/// Panics if the derived document fails to serialize to JSON, which cannot
/// happen for the statically defined schema.
#[must_use]
pub fn openapi_json_value() -> serde_json::Value {
    let mut doc =
        serde_json::to_value(openapi_document()).expect("openapi document serializes to json");
    inject_websocket_methods(&mut doc);
    inject_cross_cutting_responses(&mut doc);
    inject_optional_request_bodies(&mut doc);
    inject_provenance(&mut doc);
    doc
}

/// Render the canonical `OpenAPI` JSON document (pretty-printed, trailing
/// newline).
///
/// # Panics
/// Panics if the document fails to serialize to JSON, which cannot happen for
/// the statically defined schema.
#[must_use]
pub fn openapi_json_string() -> String {
    let mut rendered =
        serde_json::to_string_pretty(&openapi_json_value()).expect("openapi json value serializes");
    rendered.push('\n');
    rendered
}

/// Attach the mirrored `WebSocket` method name to every operation whose route
/// the contract marks as having `WebSocket` parity. Exempt routes and routes
/// absent from the contract (for example the remote-execution transport) get no
/// extension, matching [`HttpRouteParity::ws_method`].
fn inject_websocket_methods(doc: &mut serde_json::Value) {
    let Some(paths) = doc
        .get_mut("paths")
        .and_then(serde_json::Value::as_object_mut)
    else {
        return;
    };
    for (path, item) in paths.iter_mut() {
        let Some(item) = item.as_object_mut() else {
            continue;
        };
        for (method_key, operation) in item.iter_mut() {
            let Some(method) = parse_route_method(method_key) else {
                continue;
            };
            let Some(operation) = operation.as_object_mut() else {
                continue;
            };
            if let Some(ws_method) = contract_ws_method(method, path) {
                operation.insert(
                    "x-websocket-method".to_owned(),
                    serde_json::Value::String(ws_method.to_owned()),
                );
            }
        }
    }
}

/// Record how the document was produced. JSON cannot carry comments, so the
/// provenance banner lives in a top-level vendor extension.
fn inject_provenance(doc: &mut serde_json::Value) {
    if let Some(root) = doc.as_object_mut() {
        root.insert(
            "x-generated-by".to_owned(),
            serde_json::json!({
                "tool": "tools/openapi-codegen",
                "command": "mise run openapi:generate",
                "note": "Generated file. Do not edit by hand - rerun: mise run openapi:generate",
            }),
        );
    }
}

/// Operations whose handler accepts an optional request body
/// (`Option<Json<..>>`). `utoipa` marks every declared `request_body` as
/// required, so the optional ones are relaxed here at the JSON layer.
const OPTIONAL_REQUEST_BODIES: &[(&str, &str)] = &[("post", "/v1/sessions/{session_id}/observe")];

/// Mark the request body optional for operations whose handler tolerates a
/// missing body, since `utoipa` cannot express `required = false` on
/// `request_body`.
fn inject_optional_request_bodies(doc: &mut serde_json::Value) {
    let Some(paths) = doc
        .get_mut("paths")
        .and_then(serde_json::Value::as_object_mut)
    else {
        return;
    };
    for (method, path) in OPTIONAL_REQUEST_BODIES {
        let Some(request_body) = paths
            .get_mut(*path)
            .and_then(serde_json::Value::as_object_mut)
            .and_then(|item| item.get_mut(*method))
            .and_then(serde_json::Value::as_object_mut)
            .and_then(|operation| operation.get_mut("requestBody"))
            .and_then(serde_json::Value::as_object_mut)
        else {
            continue;
        };
        request_body.insert("required".to_owned(), serde_json::Value::Bool(false));
    }
}

fn parse_route_method(key: &str) -> Option<HttpRouteMethod> {
    match key {
        "get" => Some(HttpRouteMethod::Get),
        "post" => Some(HttpRouteMethod::Post),
        "put" => Some(HttpRouteMethod::Put),
        "delete" => Some(HttpRouteMethod::Delete),
        _ => None,
    }
}

fn contract_ws_method(method: HttpRouteMethod, path: &str) -> Option<&'static str> {
    HTTP_API_CONTRACT
        .iter()
        .find(|route| route.method == method && route.path == path)
        .and_then(|route| route.parity.ws_method())
}

/// A response the daemon's auth, admission, or body-limit middleware can return
/// before any handler runs. All share the [`DaemonErrorBody`] shape.
struct SharedResponse {
    component: &'static str,
    status: &'static str,
    description: &'static str,
    requires_body: bool,
}

/// Cross-cutting responses produced by remote-mode middleware. They are
/// identical for every route, so they are defined once under
/// `components/responses` and referenced from every operation instead of being
/// repeated in each `#[utoipa::path]`.
const SHARED_RESPONSES: &[SharedResponse] = &[
    SharedResponse {
        component: "RemoteAuthRequired",
        status: "401",
        description: "Missing, invalid, or unauthorized daemon credentials",
        requires_body: false,
    },
    SharedResponse {
        component: "RemoteRequestUriTooLong",
        status: "414",
        description: "Request URI exceeds the configured remote limit",
        requires_body: false,
    },
    SharedResponse {
        component: "RemoteRequestBodyTooLarge",
        status: "413",
        description: "Request body exceeds the configured remote limit",
        requires_body: true,
    },
    SharedResponse {
        component: "RemoteRequestHeadersTooLarge",
        status: "431",
        description: "Request headers exceed the configured remote limit",
        requires_body: false,
    },
    SharedResponse {
        component: "RemoteRequestThrottled",
        status: "429",
        description: "Remote request or connection concurrency limit reached",
        requires_body: false,
    },
    SharedResponse {
        component: "RemoteServiceUnavailable",
        status: "503",
        description: "Remote auth store or request limits unavailable",
        requires_body: false,
    },
    SharedResponse {
        component: "RemoteRequestTimedOut",
        status: "504",
        description: "Remote request exceeded the configured timeout",
        requires_body: false,
    },
];

/// Document the cross-cutting middleware responses once and reference them from
/// every operation, so the schema reflects what a client can receive before a
/// handler runs without repeating the set per route. Body-size limits only
/// apply to operations that carry a request body.
fn inject_cross_cutting_responses(doc: &mut serde_json::Value) {
    define_shared_responses(doc);
    reference_shared_responses(doc);
}

fn define_shared_responses(doc: &mut serde_json::Value) {
    let Some(components) = doc
        .get_mut("components")
        .and_then(serde_json::Value::as_object_mut)
    else {
        return;
    };
    let responses = components
        .entry("responses")
        .or_insert_with(|| serde_json::Value::Object(serde_json::Map::new()));
    let Some(responses) = responses.as_object_mut() else {
        return;
    };
    for shared in SHARED_RESPONSES {
        responses.insert(
            shared.component.to_owned(),
            serde_json::json!({
                "description": shared.description,
                "content": {
                    "application/json": {
                        "schema": { "$ref": "#/components/schemas/DaemonErrorBody" }
                    }
                }
            }),
        );
    }
}

fn reference_shared_responses(doc: &mut serde_json::Value) {
    let Some(paths) = doc
        .get_mut("paths")
        .and_then(serde_json::Value::as_object_mut)
    else {
        return;
    };
    for item in paths.values_mut() {
        let Some(item) = item.as_object_mut() else {
            continue;
        };
        for (method, operation) in item.iter_mut() {
            if parse_route_method(method).is_none() {
                continue;
            }
            if let Some(operation) = operation.as_object_mut() {
                add_shared_response_refs(operation);
            }
        }
    }
}

fn add_shared_response_refs(operation: &mut serde_json::Map<String, serde_json::Value>) {
    let has_body = operation.contains_key("requestBody");
    let responses = operation
        .entry("responses")
        .or_insert_with(|| serde_json::Value::Object(serde_json::Map::new()));
    let Some(responses) = responses.as_object_mut() else {
        return;
    };
    for shared in SHARED_RESPONSES {
        if shared.requires_body && !has_body {
            continue;
        }
        responses
            .entry(shared.status.to_owned())
            .or_insert_with(|| {
                serde_json::json!({
                    "$ref": format!("#/components/responses/{}", shared.component)
                })
            });
    }
}
