//! `OpenAPI` 3.1 document generation for the daemon HTTP API.
//!
//! The document is assembled from `#[utoipa::path]` annotations on the daemon
//! handlers plus `#[derive(utoipa::ToSchema)]` on their request and response
//! types. Per-domain [`utoipa::OpenApi`] aggregators are merged into a single
//! document; `x-websocket-method` extensions and generator provenance are
//! injected at the JSON layer from the authoritative [`HTTP_API_CONTRACT`].
//!
//! This module compiles only under the `openapi` feature. The checked-in
//! artifact `docs/api/openapi.json` is regenerated by `tools/openapi-codegen`
//! (`mise run openapi:generate`) and drift-checked by `mise run openapi:check`.

use serde::{Deserialize, Serialize};
use utoipa::OpenApi;

use crate::daemon::protocol::{HTTP_API_CONTRACT, HttpRouteMethod};

/// Error envelope returned by daemon handlers on failure.
///
/// Mirrors the dominant shape produced by `error_status_and_body`
/// (`{"error": {"code", "message", "details"}}`). A few endpoints emit
/// alternate ad-hoc error shapes for specific conditions; those are noted in
/// the relevant operation descriptions.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct DaemonErrorBody {
    pub error: DaemonErrorDetail,
}

/// Structured error detail carried by [`DaemonErrorBody`].
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct DaemonErrorDetail {
    /// Stable machine-readable error code (for example `SESSION_SCOPE_DENIED`).
    pub code: String,
    /// Human-readable error message.
    pub message: String,
    /// Optional additional context lines.
    #[serde(default)]
    pub details: Vec<String>,
}

#[derive(utoipa::OpenApi)]
#[openapi(
    info(
        title = "Harness daemon API",
        description = "REST API served by the Harness daemon (harness-daemon). The API is dual-transport: most endpoints mirror a WebSocket JSON-RPC method, recorded per operation as the `x-websocket-method` extension. Generated from annotated handlers - do not edit docs/api/openapi.json by hand; regenerate with `mise run openapi:generate`."
    ),
    components(schemas(DaemonErrorBody, DaemonErrorDetail))
)]
struct HarnessDaemonApi;

#[derive(utoipa::OpenApi)]
#[openapi(paths(
    super::core::get_health,
    super::core::get_ready,
    super::core::post_stop_daemon,
    super::core::get_log_level,
    super::core::put_log_level,
    super::core::post_daemon_telemetry,
    super::core::get_projects,
    super::core::get_runtime_session_resolution,
))]
struct CoreApi;

/// Build the typed `OpenAPI` document from every domain aggregator.
///
/// Aggregators merge in registration order; component schemas deduplicate by
/// name. As new route domains are annotated in later slices, add their
/// aggregator's `merge` call here.
#[must_use]
pub fn openapi_document() -> utoipa::openapi::OpenApi {
    let mut doc = HarnessDaemonApi::openapi();
    doc.merge(CoreApi::openapi());
    env!("CARGO_PKG_VERSION").clone_into(&mut doc.info.version);
    doc
}

/// Render the `OpenAPI` document as a canonical JSON value with
/// `x-websocket-method` extensions and generator provenance injected.
///
/// # Panics
/// Panics if the derived document fails to serialize to JSON, which cannot
/// happen for the statically defined schema.
#[must_use]
pub fn openapi_json_value() -> serde_json::Value {
    let mut doc =
        serde_json::to_value(openapi_document()).expect("openapi document serializes to json");
    inject_websocket_methods(&mut doc);
    inject_provenance(&mut doc);
    doc
}

/// Render the canonical `OpenAPI` JSON document (pretty-printed, trailing
/// newline).
///
/// # Panics
/// Panics if the document fails to serialize to JSON, which cannot happen for
/// the statically defined schema.
#[must_use]
pub fn openapi_json_string() -> String {
    let mut rendered =
        serde_json::to_string_pretty(&openapi_json_value()).expect("openapi json value serializes");
    rendered.push('\n');
    rendered
}

/// Attach the mirrored `WebSocket` method name to every operation whose route
/// the contract marks as having `WebSocket` parity. Exempt routes and routes
/// absent from the contract (for example the remote-execution transport) get no
/// extension, matching [`HttpRouteParity::ws_method`].
fn inject_websocket_methods(doc: &mut serde_json::Value) {
    let Some(paths) = doc
        .get_mut("paths")
        .and_then(serde_json::Value::as_object_mut)
    else {
        return;
    };
    for (path, item) in paths.iter_mut() {
        let Some(item) = item.as_object_mut() else {
            continue;
        };
        for (method_key, operation) in item.iter_mut() {
            let Some(method) = parse_route_method(method_key) else {
                continue;
            };
            let Some(operation) = operation.as_object_mut() else {
                continue;
            };
            if let Some(ws_method) = contract_ws_method(method, path) {
                operation.insert(
                    "x-websocket-method".to_owned(),
                    serde_json::Value::String(ws_method.to_owned()),
                );
            }
        }
    }
}

/// Record how the document was produced. JSON cannot carry comments, so the
/// provenance banner lives in a top-level vendor extension.
fn inject_provenance(doc: &mut serde_json::Value) {
    if let Some(root) = doc.as_object_mut() {
        root.insert(
            "x-generated-by".to_owned(),
            serde_json::json!({
                "tool": "tools/openapi-codegen",
                "command": "mise run openapi:generate",
                "note": "Generated file. Do not edit by hand - rerun: mise run openapi:generate",
            }),
        );
    }
}

fn parse_route_method(key: &str) -> Option<HttpRouteMethod> {
    match key {
        "get" => Some(HttpRouteMethod::Get),
        "post" => Some(HttpRouteMethod::Post),
        "put" => Some(HttpRouteMethod::Put),
        "delete" => Some(HttpRouteMethod::Delete),
        _ => None,
    }
}

fn contract_ws_method(method: HttpRouteMethod, path: &str) -> Option<&'static str> {
    HTTP_API_CONTRACT
        .iter()
        .find(|route| route.method == method && route.path == path)
        .and_then(|route| route.parity.ws_method())
}
