//! Task-board domain [`utoipa::OpenApi`] aggregator. Kept in its own module
//! because the 48-operation path list would push `openapi/mod.rs` past the
//! file-length cap.

#[derive(utoipa::OpenApi)]
#[openapi(paths(
    super::super::task_board::items::get_task_board_capabilities,
    super::super::task_board::items::post_task_board_item,
    super::super::task_board::items::get_task_board_items,
    super::super::task_board::items::get_task_board_item,
    super::super::task_board::items::put_task_board_item,
    super::super::task_board::items::delete_task_board_item,
    super::super::task_board::items::post_task_board_plan_begin,
    super::super::task_board::items::post_task_board_plan_submit,
    super::super::task_board::items::post_task_board_plan_approve,
    super::super::task_board::items::post_task_board_plan_revoke,
    super::super::task_board::operations::post_task_board_sync,
    super::super::task_board::operations::post_task_board_dispatch,
    super::super::task_board::operations::post_task_board_dispatch_deliver,
    super::super::task_board::operations::post_task_board_dispatch_pick,
    super::super::task_board::operations::post_task_board_evaluate,
    super::super::task_board::operations::get_task_board_audit,
    super::super::task_board::operations::get_task_board_projects,
    super::super::task_board::operations::get_task_board_machines,
    super::super::task_board::operations::get_task_board_host_local,
    super::super::task_board::operations::get_task_board_host_list,
    super::super::task_board::operations::put_task_board_host_set_project_types,
    super::super::task_board::positions::get_task_board_item_position_snapshot,
    super::super::task_board::positions::put_task_board_item_position,
    super::super::task_board::positions::post_task_board_item_position_reset,
    super::super::task_board::triage::get_task_board_item_triage,
    super::super::task_board::triage::get_task_board_item_triage_history,
    super::super::task_board::triage::put_task_board_item_triage_override,
    super::super::task_board::triage::post_task_board_item_triage_override_clear,
    super::super::task_board_orchestrator_handlers::get_task_board_orchestrator_status,
    super::super::task_board_orchestrator_handlers::post_task_board_orchestrator_start,
    super::super::task_board_orchestrator_handlers::post_task_board_orchestrator_stop,
    super::super::task_board_orchestrator_handlers::post_task_board_orchestrator_run_once,
    super::super::task_board_orchestrator_handlers::get_task_board_automation_runs,
    super::super::task_board_orchestrator_handlers::get_task_board_automation_run_detail,
    super::super::task_board_orchestrator_handlers::get_task_board_automation_metrics,
    super::super::task_board_orchestrator_handlers::post_task_board_automation_force_cancel,
    super::super::task_board_orchestrator_handlers::get_task_board_orchestrator_settings,
    super::super::task_board_orchestrator_handlers::put_task_board_orchestrator_settings,
    super::super::task_board_git::get_task_board_orchestrator_runtime_config,
    super::super::task_board_git::put_task_board_orchestrator_runtime_config,
    super::super::task_board_git::put_task_board_orchestrator_github_tokens,
    super::super::task_board_git::put_task_board_orchestrator_todoist_token,
    super::super::task_board_git::put_task_board_orchestrator_openrouter_token,
    super::super::task_board_git::get_task_board_git_identity_defaults,
    super::super::task_board_git::post_task_board_git_signing_verify,
    super::super::task_board_git::put_task_board_git_runtime_key_material,
    super::super::task_board_git::post_task_board_git_runtime_secret_handoff_prepare,
    super::super::task_board_git::post_task_board_git_runtime_secret_handoff_ack,
))]
pub(super) struct TaskBoardApi;
