use super::*;

#[test]
fn review_routes_have_complete_ws_parity() {
    let review_routes = super::routes_reviews::ROUTES;
    let actual: Vec<_> = review_routes
        .iter()
        .map(|route| {
            let ws_method = route
                .parity
                .ws_method()
                .expect("reviews route should map to websocket");
            (
                route.method,
                route.path,
                ws_method,
                route.swift_client_exposed,
            )
        })
        .collect();
    assert_eq!(
        actual,
        vec![
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_REPOSITORIES,
                ws_methods::REVIEWS_REPOSITORY_CATALOG,
                true,
            ),
            (
                HttpRouteMethod::Get,
                http_paths::REVIEWS_CAPABILITIES,
                ws_methods::REVIEWS_CAPABILITIES,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_QUERY,
                ws_methods::REVIEWS_QUERY,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_PULL_REQUEST_RESOLVE,
                ws_methods::REVIEWS_PULL_REQUEST_RESOLVE,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_ACTION_PREVIEW,
                ws_methods::REVIEWS_ACTION_PREVIEW,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_POLICY_PREVIEW,
                ws_methods::REVIEWS_POLICY_PREVIEW,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_POLICY_START,
                ws_methods::REVIEWS_POLICY_START,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_POLICY_STATUS,
                ws_methods::REVIEWS_POLICY_STATUS,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_POLICY_HISTORY,
                ws_methods::REVIEWS_POLICY_HISTORY,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_APPROVE,
                ws_methods::REVIEWS_APPROVE,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_MERGE,
                ws_methods::REVIEWS_MERGE,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_RERUN_CHECKS,
                ws_methods::REVIEWS_RERUN_CHECKS,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_LABELS,
                ws_methods::REVIEWS_ADD_LABEL,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_AUTO,
                ws_methods::REVIEWS_AUTO,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_REQUEST_REVIEW,
                ws_methods::REVIEWS_REQUEST_REVIEW,
                true,
            ),
            (
                HttpRouteMethod::Delete,
                http_paths::REVIEWS_CACHE,
                ws_methods::REVIEWS_CLEAR_CACHE,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_REFRESH,
                ws_methods::REVIEWS_REFRESH,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_BODY,
                ws_methods::REVIEWS_BODY,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_BODY_UPDATE,
                ws_methods::REVIEWS_BODY_UPDATE,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_COMMENT,
                ws_methods::REVIEWS_COMMENT,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_FILES_LIST,
                ws_methods::REVIEWS_FILES_LIST,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_FILES_COMMENT,
                ws_methods::REVIEWS_FILES_COMMENT,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_FILES_PATCH,
                ws_methods::REVIEWS_FILES_PATCH,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_FILES_PREVIEW,
                ws_methods::REVIEWS_FILES_PREVIEW,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_FILES_VIEWED,
                ws_methods::REVIEWS_FILES_VIEWED,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_FILES_BLOB,
                ws_methods::REVIEWS_FILES_BLOB,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_FILES_LOCAL_CLONES,
                ws_methods::REVIEWS_FILES_LOCAL_CLONES_LIST,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_FILES_LOCAL_CLONES_DELETE,
                ws_methods::REVIEWS_FILES_LOCAL_CLONES_DELETE,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_AVATAR,
                ws_methods::REVIEWS_AVATAR,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_TIMELINE,
                ws_methods::REVIEWS_TIMELINE,
                true,
            ),
            (
                HttpRouteMethod::Post,
                http_paths::REVIEWS_REVIEW_THREADS_RESOLVE,
                ws_methods::REVIEWS_REVIEW_THREADS_RESOLVE,
                true,
            ),
        ]
    );
}
