import HarnessMonitorKit
import SwiftUI

struct SessionWindowCreateFormMetrics: Equatable {
  let formPadding: CGFloat
  let promptMinHeight: CGFloat
  let submitButtonMinHeight: CGFloat

  init(fontScale: CGFloat) {
    let scale = SessionWindowFontScale.metricsScale(for: fontScale)
    formPadding = 24 * min(scale, 1.3)
    promptMinHeight = max(90, 90 * min(scale, 1.25))
    submitButtonMinHeight = scale >= 1.45 ? 44 : 0
  }
}

private struct SessionWindowCreateFormStateStorage {
  var validationResult: SessionWindowCreateFormValidationResult?
  var lastAutoGeneratedName = ""
}

struct SessionWindowCreateForm: View {
  let store: HarnessMonitorStore
  let state: SessionWindowStateCache
  let draft: SessionCreateDraft
  let embedsRuntimeConfiguration: Bool
  @Environment(\.fontScale)
  private var fontScale
  @State private var stateStorage = SessionWindowCreateFormStateStorage()
  @FocusState private var focusedFieldStorage: SessionWindowCreateFormField?

  private var title: Binding<String> {
    Binding(
      get: { draft.title },
      set: { updateDraft(title: $0) }
    )
  }

  private var prompt: Binding<String> {
    Binding(
      get: { draft.prompt },
      set: { updateDraft(prompt: $0) }
    )
  }

  private var taskSeverity: Binding<TaskSeverity> {
    Binding(
      get: { draft.taskSeverity },
      set: { updateDraft(taskSeverity: $0) }
    )
  }

  var validationResult: SessionWindowCreateFormValidationResult? {
    get { stateStorage.validationResult }
    nonmutating set { stateStorage.validationResult = newValue }
  }

  var lastAutoGeneratedName: String {
    get { stateStorage.lastAutoGeneratedName }
    nonmutating set { stateStorage.lastAutoGeneratedName = newValue }
  }

  var focusedField: SessionWindowCreateFormField? {
    get { focusedFieldStorage }
    nonmutating set { focusedFieldStorage = newValue }
  }

  var focusedFieldBinding: FocusState<SessionWindowCreateFormField?>.Binding {
    $focusedFieldStorage
  }

  var activeAgentCapabilityOptions: [AgentCapabilityOption] {
    SessionWindowCreateFormCatalogs.activeAgentOptions(
      catalogState: state.agentCreateCatalog,
      store: store
    )
  }

  private var metrics: SessionWindowCreateFormMetrics {
    SessionWindowCreateFormMetrics(fontScale: fontScale)
  }

  var body: some View {
    Form {
      if draft.kind == .agent, embedsRuntimeConfiguration {
        embeddedAgentRuntimeSections
      }
      Section {
        HStack(spacing: 6) {
          TextField("Name", text: title)
            .scaledFont(.body)
            .focused(focusedFieldBinding, equals: .name)
            .accessibilityLabel("\(draft.kind.title) name")
            .accessibilityHint(validationMessage(for: .name) ?? "")
          if draft.kind == .agent {
            Button {
              regenerateAgentName()
            } label: {
              Image(systemName: "arrow.clockwise")
            }
            .buttonStyle(.borderless)
            .help("Generate a new agent name")
            .accessibilityLabel("Regenerate agent name")
          }
        }
        TextEditor(text: prompt)
          .scaledFont(.body)
          .frame(minHeight: metrics.promptMinHeight)
          .focused(focusedFieldBinding, equals: .prompt)
          .accessibilityLabel("Prompt")
      } header: {
        Text(draft.kind.title)
          .harnessNativeFormSectionHeader()
      }
      if draft.kind == .agent, let agentBridgeBannerKind {
        Section {
          SessionCreateBridgeBanner(
            store: store,
            copy: agentBridgeBannerKind.copy(store: store)
          )
        }
      }
      if draft.kind == .agent {
        agentConfigurationSections
      }
      if draft.kind == .task {
        Section {
          Picker("Severity", selection: taskSeverity) {
            ForEach(TaskSeverity.allCases, id: \.rawValue) { severity in
              Text(severity.title).tag(severity)
            }
          }
          .accessibilityLabel("Task severity")
        } header: {
          Text("Task Details")
            .harnessNativeFormSectionHeader()
        }
      }
      if let validationResult {
        Section {
          Text(validationResult.message)
            .scaledFont(.callout)
            .foregroundStyle(.red)
            .accessibilityLabel("Validation error: \(validationResult.message)")
        }
      }
      Section {
        HStack {
          Button("Cancel", role: .cancel) {
            cancel()
          }
          Spacer()
          Button {
            Task { await submit() }
          } label: {
            Label("Create", systemImage: "plus.circle.fill")
              .scaledFont(.body.weight(.semibold))
          }
          .frame(minHeight: metrics.submitButtonMinHeight)
          .keyboardShortcut(.defaultAction)
        }
      }
    }
    .harnessNativeFormContainer()
    .contentMargins(.horizontal, metrics.formPadding, for: .scrollContent)
    .contentMargins(.vertical, metrics.formPadding, for: .scrollContent)
    .scrollContentBackground(.hidden)
    .dynamicTypeSize(.xSmall ... .accessibility5)
    .task {
      if focusedField == nil {
        focusedField = .name
      }
      prefillAgentNameIfEligible()
      if draft.kind == .agent, embedsRuntimeConfiguration {
        await SessionWindowCreateFormCatalogs.loadAgentCatalogStateIfNeeded(
          store: store,
          state: state,
          draft: draft
        )
      }
    }
    .onChange(of: draft.runtime) { _, _ in
      prefillAgentNameIfEligible()
      clearValidationIfResolved()
    }
    .onChange(of: draft.prompt) { _, _ in
      clearValidationIfResolved()
    }
  }

  func updateDraft(
    title: String? = nil,
    prompt: String? = nil,
    runtime: String? = nil,
    role: SessionRole? = nil,
    fallbackRole: SessionRole? = nil,
    personaID: String? = nil,
    projectDir: String? = nil,
    argvOverride: String? = nil,
    taskSeverity: TaskSeverity? = nil,
    codexMode: CodexRunMode? = nil,
    codexModel: String? = nil,
    codexEffort: String? = nil,
    codexAllowCustomModel: Bool? = nil
  ) {
    var next = draft
    if let title {
      next.title = title
    }
    if let prompt {
      next.prompt = prompt
    }
    if let runtime {
      next.runtime = runtime
    }
    if let role {
      next.role = role
    }
    if let fallbackRole {
      next.fallbackRole = fallbackRole
    }
    if let personaID {
      next.personaID = personaID
    }
    if let projectDir {
      next.projectDir = projectDir
    }
    if let argvOverride {
      next.argvOverride = argvOverride
    }
    if let taskSeverity {
      next.taskSeverity = taskSeverity
    }
    if let codexMode {
      next.codexMode = codexMode
    }
    if let codexModel {
      next.codexModel = codexModel
    }
    if let codexEffort {
      next.codexEffort = codexEffort
    }
    if let codexAllowCustomModel {
      next.codexAllowCustomModel = codexAllowCustomModel
    }
    clearValidationIfNeeded(title: title, runtime: runtime)
    state.updateCreateDraft(next)
  }

  private func cancel() {
    validationResult = nil
    state.cancelCreateDraft(draft.kind)
  }
}

enum SessionWindowCreateFormField: Hashable {
  case name
  case prompt
}

extension SessionWindowCreateForm {
  private var catalogState: SessionWindowAgentCreateCatalogState {
    state.agentCreateCatalog
  }

  private var activePersonas: [AgentPersona] {
    catalogState.personas
  }

  private var normalizedLaunchSelection: AgentLaunchSelection {
    SessionWindowCreateFormCatalogs.normalizedLaunchSelection(
      draft: draft,
      options: activeAgentCapabilityOptions
    )
  }

  private var selectedCapabilityOption: AgentCapabilityOption? {
    SessionWindowCreateFormCatalogs.selectedCapabilityOption(
      selection: normalizedLaunchSelection,
      options: activeAgentCapabilityOptions
    )
  }

  private var selectedTransportChoice: AgentCapabilityTransportChoice? {
    selectedCapabilityOption.map { option in
      option.transportChoice(for: normalizedLaunchSelection)
    }
  }

  private var selectedProviderID: Binding<String> {
    Binding(
      get: { selectedCapabilityOption?.id ?? "" },
      set: { newValue in
        guard
          let option = activeAgentCapabilityOptions.first(where: { $0.id == newValue })
        else {
          return
        }
        selectProvider(option)
      }
    )
  }

  private var selectedTerminalRuntime: AgentTuiRuntime? {
    guard case .tui(let runtime) = normalizedLaunchSelection else { return nil }
    return runtime
  }

  private var selectedTerminalCatalog: RuntimeModelCatalog? {
    guard let selectedTerminalRuntime else { return nil }
    return SessionWindowCreateFormCatalogs.selectedModelCatalog(
      selection: .tui(selectedTerminalRuntime),
      catalogState: catalogState
    )
  }

  private var codexCatalog: RuntimeModelCatalog? {
    SessionWindowCreateFormCatalogs.codexModelCatalog(catalogState: catalogState)
  }

  private var showsAcpFallbackRoleMenu: Bool {
    SessionWindowCreateFormCatalogs.shouldShowAcpFallbackRole(
      selection: normalizedLaunchSelection,
      role: draft.role
    )
  }

  private var agentBridgeBannerKind: SessionCreateBridgeBannerKind? {
    guard draft.kind == .agent else { return nil }
    if normalizedLaunchSelection.isAcp {
      return store.acpUnavailable ? .acp : nil
    }
    return store.agentTuiUnavailable ? .agentTui : nil
  }

  private var launchSelection: Binding<AgentLaunchSelection> {
    Binding(
      get: { normalizedLaunchSelection },
      set: { updateDraft(runtime: $0.storageKey) }
    )
  }

  private var selectedRole: Binding<SessionRole> {
    Binding(
      get: { draft.role },
      set: { updateDraft(role: $0) }
    )
  }

  private var selectedFallbackRole: Binding<SessionRole> {
    Binding(
      get: { draft.fallbackRole },
      set: { updateDraft(fallbackRole: $0) }
    )
  }

  private var selectedPersonaID: Binding<String> {
    Binding(
      get: { draft.personaID },
      set: { updateDraft(personaID: $0) }
    )
  }

  private var projectDirOverride: Binding<String> {
    Binding(
      get: { draft.projectDir },
      set: { updateDraft(projectDir: $0) }
    )
  }

  private var argvOverrideText: Binding<String> {
    Binding(
      get: { draft.argvOverride },
      set: { updateDraft(argvOverride: $0) }
    )
  }

  private var codexMode: Binding<CodexRunMode> {
    Binding(
      get: { draft.codexMode },
      set: { updateDraft(codexMode: $0) }
    )
  }

  private var codexModelPickerSelection: Binding<String> {
    Binding(
      get: {
        if draft.codexAllowCustomModel {
          return SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag
        }
        let stored = draft.codexModel.trimmingCharacters(in: .whitespacesAndNewlines)
        if !stored.isEmpty {
          return stored
        }
        return codexCatalog?.default ?? SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag
      },
      set: { newValue in
        if newValue == SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag {
          updateDraft(codexAllowCustomModel: true)
        } else {
          updateDraft(
            codexModel: newValue,
            codexAllowCustomModel: false
          )
        }
      }
    )
  }

  private var codexCustomModel: Binding<String> {
    Binding(
      get: { draft.codexAllowCustomModel ? draft.codexModel : "" },
      set: {
        updateDraft(
          codexModel: $0,
          codexAllowCustomModel: true
        )
      }
    )
  }

  private var codexEffortValues: [String] {
    guard let codexCatalog else {
      return codexModelPickerSelection.wrappedValue
        == SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag
        ? SessionWindowCreateFormCatalogs.allEffortLevels
        : []
    }
    return SessionWindowCreateFormCatalogs.effortValues(
      catalog: codexCatalog,
      selectedModelID: codexModelPickerSelection.wrappedValue
    )
  }

  private var codexEffortSelection: Binding<String> {
    Binding(
      get: {
        let current = draft.codexEffort.trimmingCharacters(in: .whitespacesAndNewlines)
        guard codexEffortValues.contains(current) else {
          return SessionWindowCreateFormCatalogs.defaultEffortLevel(from: codexEffortValues)
        }
        return current
      },
      set: { updateDraft(codexEffort: $0) }
    )
  }

  @ViewBuilder private var agentConfigurationSections: some View {
    terminalConfigurationSections
  }

  @ViewBuilder private var embeddedAgentRuntimeSections: some View {
    Section {
      if catalogState.isLoading && !catalogState.hasLoaded {
        Label("Checking available runtimes", systemImage: "clock")
          .scaledFont(.caption)
          .foregroundStyle(HarnessMonitorTheme.secondaryInk)
      }
      if let capabilityValidation = validationMessage(for: .capability) {
        Text(capabilityValidation)
          .scaledFont(.caption)
          .foregroundStyle(.red)
          .fixedSize(horizontal: false, vertical: true)
      }

      Picker("Provider", selection: selectedProviderID) {
        ForEach(activeAgentCapabilityOptions) { option in
          Text(option.title).tag(option.id)
        }
      }
      .pickerStyle(.menu)
      .harnessNativeFormControl()
      .accessibilityLabel("Provider")
    } header: {
      Text("Provider")
        .harnessNativeFormSectionHeader()
    } footer: {
      Text(embeddedProviderDescription)
        .harnessNativeFormSectionFooter()
    }
  }

  private var embeddedProviderDescription: String {
    if let option = selectedCapabilityOption, let choice = selectedTransportChoice {
      let summary = SessionWindowCreateFormCatalogs.transportSummary(option: option, choice: choice)
      return "\(summary) Finish the remaining setup in the sections below."
    }
    return
      "Choose how this agent starts. The remaining form sections hold the configuration "
      + "and advanced overrides."
  }

  @ViewBuilder private var terminalConfigurationSections: some View {
    if let option = selectedCapabilityOption, option.transportChoices.count > 1 {
      terminalTransportChoicesSection(option: option)
    } else if !embedsRuntimeConfiguration, selectedCapabilityOption == nil {
      Section {
        Text("Choose a provider in the middle pane to configure this agent.")
          .scaledFont(.caption)
          .foregroundStyle(HarnessMonitorTheme.secondaryInk)
          .fixedSize(horizontal: false, vertical: true)
      } header: {
        Text("Provider")
          .harnessNativeFormSectionHeader()
      }
    }

    terminalRuntimeConfigurationSection
    terminalSessionSection
    terminalAdvancedOverridesSection
  }

  private var terminalSessionSection: some View {
    Section {
      Picker("Role", selection: selectedRole) {
        ForEach(SessionRole.allCases, id: \.self) { role in
          Text(role.title).tag(role)
        }
      }
      .pickerStyle(.menu)
      .harnessNativeFormControl()
      .accessibilityLabel("Role")

      if showsAcpFallbackRoleMenu {
        Picker("Fallback role", selection: selectedFallbackRole) {
          ForEach(SessionRole.allCases.filter { $0 != .leader }, id: \.self) { role in
            Text(role.title).tag(role)
          }
        }
        .pickerStyle(.menu)
        .harnessNativeFormControl()
        .accessibilityLabel("Fallback role")
      }
      Picker("Persona", selection: selectedPersonaID) {
        Text("None").tag("")
        ForEach(activePersonas, id: \.identifier) { persona in
          Text(persona.name).tag(persona.identifier)
        }
      }
      .pickerStyle(.menu)
      .harnessNativeFormControl()
      .accessibilityLabel("Persona")
    } header: {
      Text("Session")
        .harnessNativeFormSectionHeader()
    } footer: {
      Text(
        SessionWindowCreateFormCatalogs.selectedPersonaStateText(
          personaID: draft.personaID,
          personas: activePersonas
        )
      )
      .harnessNativeFormSectionFooter()
    }
  }

  private var terminalAdvancedOverridesSection: some View {
    Section {
      TextField("Optional project directory override", text: projectDirOverride)
        .harnessNativeTextField()
        .accessibilityLabel("Project directory override")

      if !normalizedLaunchSelection.isAcp {
        TextEditor(text: argvOverrideText)
          .scaledFont(.body)
          .frame(minHeight: 100)
          .accessibilityLabel("Command override")
      }
    } header: {
      Text("Advanced overrides")
        .harnessNativeFormSectionHeader()
    } footer: {
      Text(advancedOverridesDescription)
        .harnessNativeFormSectionFooter()
    }
  }

  private var advancedOverridesDescription: String {
    if normalizedLaunchSelection.isAcp {
      return "Set an optional project directory override for this agent."
    }
    return
      "Set an optional project directory override. Use one argument per line for a "
      + "command override; the first line is the executable."
  }

  @ViewBuilder
  private func terminalTransportChoicesSection(option: AgentCapabilityOption) -> some View {
    if option.transportChoices.count > 1 {
      Section {
        ViewThatFits(in: .horizontal) {
          HStack(alignment: .top, spacing: HarnessMonitorTheme.spacingSM) {
            ForEach(option.transportChoices) { transportChoice in
              SessionWindowCreateTransportChoiceButton(
                providerTitle: option.title,
                choice: transportChoice,
                selection: launchSelection,
                isSelected: normalizedLaunchSelection == transportChoice.id,
                isEnabled: option.isEnabled(transportChoice),
                unavailableReason: SessionWindowCreateFormCatalogs.unavailableReason(
                  for: option,
                  choice: transportChoice
                )
              )
            }
          }

          VStack(alignment: .leading, spacing: HarnessMonitorTheme.spacingSM) {
            ForEach(option.transportChoices) { transportChoice in
              SessionWindowCreateTransportChoiceButton(
                providerTitle: option.title,
                choice: transportChoice,
                selection: launchSelection,
                isSelected: normalizedLaunchSelection == transportChoice.id,
                isEnabled: option.isEnabled(transportChoice),
                unavailableReason: SessionWindowCreateFormCatalogs.unavailableReason(
                  for: option,
                  choice: transportChoice
                )
              )
            }
          }
        }

        if let choice = selectedTransportChoice {
          terminalTransportNotice(option: option, choice: choice)
        }
      } header: {
        Text("Start with")
          .harnessNativeFormSectionHeader()
      } footer: {
        Text("Choose whether this provider opens in Terminal or joins with project access.")
          .harnessNativeFormSectionFooter()
      }
    }
  }

  @ViewBuilder private var terminalRuntimeConfigurationSection: some View {
    let option = selectedCapabilityOption
    let choice = selectedTransportChoice

    Section {
      if let runtime = selectedTerminalRuntime, let catalog = selectedTerminalCatalog {
        let modelSelection = terminalModelPickerSelection(for: runtime, catalog: catalog)

        Picker("Model", selection: modelSelection) {
          ForEach(catalog.models) { model in
            Text(model.displayName).tag(model.id)
          }
          Text("Custom...")
            .tag(SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag)
        }
        .pickerStyle(.menu)
        .harnessNativeFormControl()
        .accessibilityLabel("Runtime model")

        if modelSelection.wrappedValue == SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag {
          TextField(
            "Provider-specific model id",
            text: terminalCustomModel(for: runtime)
          )
          .harnessNativeTextField()
          .accessibilityLabel("Custom runtime model")
        }

        let effortValues = terminalEffortValues(for: runtime, catalog: catalog)
        if !effortValues.isEmpty {
          Picker("Effort", selection: terminalEffortSelection(for: runtime, values: effortValues)) {
            ForEach(effortValues, id: \.self) { level in
              Text(level.capitalized).tag(level)
            }
          }
          .pickerStyle(.segmented)
          .harnessNativeFormControl()
          .accessibilityLabel("Runtime effort")
        }
      } else if normalizedLaunchSelection.isAcp {
        Text("Project access uses the provider's configured defaults.")
          .scaledFont(.caption)
          .foregroundStyle(HarnessMonitorTheme.secondaryInk)
          .fixedSize(horizontal: false, vertical: true)
      } else {
        Text("This runtime does not publish additional model controls here.")
          .scaledFont(.caption)
          .foregroundStyle(HarnessMonitorTheme.secondaryInk)
          .fixedSize(horizontal: false, vertical: true)
      }

      if let option, let choice, option.transportChoices.count <= 1 {
        terminalTransportNotice(option: option, choice: choice)
      }
    } header: {
      Text("Runtime")
        .harnessNativeFormSectionHeader()
    } footer: {
      if let option, let choice {
        Text(SessionWindowCreateFormCatalogs.transportSummary(option: option, choice: choice))
          .harnessNativeFormSectionFooter()
      }
    }
  }

  private func selectProvider(_ option: AgentCapabilityOption) {
    launchSelection.wrappedValue = option.normalizedSelection(for: launchSelection.wrappedValue)
  }

  @ViewBuilder
  private func terminalTransportNotice(
    option: AgentCapabilityOption,
    choice: AgentCapabilityTransportChoice
  ) -> some View {
    if let unavailableReason = SessionWindowCreateFormCatalogs.unavailableReason(
      for: option,
      choice: choice
    ),
      !option.isEnabled(choice)
    {
      Label {
        Text(unavailableReason)
          .scaledFont(.caption)
          .fixedSize(horizontal: false, vertical: true)
      } icon: {
        Image(systemName: "exclamationmark.triangle.fill")
      }
      .foregroundStyle(HarnessMonitorTheme.caution)
      .accessibilityElement(children: .combine)
    }

    if option.showsInstallCTA {
      HarnessMonitorActionButton(
        title: option.installActionTitle,
        tint: HarnessMonitorTheme.caution,
        variant: .prominent,
        accessibilityIdentifier: HarnessMonitorAccessibility.agentCapabilityInstallButton(
          option.id),
        fillsWidth: false
      ) {
        HarnessMonitorClipboard.copy(SessionWindowCreateFormCatalogs.installHintText(for: option))
      }
      .help(SessionWindowCreateFormCatalogs.installHintText(for: option))
      .accessibilityHint(option.installAccessibilityHint ?? "")
    }

    if option.availabilityState == .checkingAccess
      || option.availabilityState == .setupRequired
      || option.availabilityState == .bridgeAccessRequired
      || option.availabilityState == .unavailable
    {
      SessionWindowCreateDiagnosticsDisclosure(option: option)
    }
  }

  private var codexConfigurationSection: some View {
    Section {
      Picker("Run mode", selection: codexMode) {
        ForEach(CodexRunMode.allCases) { mode in
          Text(mode.title).tag(mode)
        }
      }
      .pickerStyle(.segmented)
      .harnessNativeFormControl()
      .accessibilityLabel("Codex mode")

      if let codexCatalog {
        Picker(
          selectedCodexModelMenuTitle(catalog: codexCatalog),
          selection: codexModelPickerSelection
        ) {
          ForEach(codexCatalog.models) { model in
            Text(model.displayName).tag(model.id)
          }
          Text("Custom...")
            .tag(SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag)
        }
        .pickerStyle(.menu)
        .harnessNativeFormControl()
        .accessibilityLabel("Codex model")

        if codexModelPickerSelection.wrappedValue
          == SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag
        {
          TextField("Provider-specific model id", text: codexCustomModel)
            .harnessNativeTextField()
            .accessibilityLabel("Custom Codex model")
        }

        if !codexEffortValues.isEmpty {
          Picker("Effort", selection: codexEffortSelection) {
            ForEach(codexEffortValues, id: \.self) { level in
              Text(level.capitalized).tag(level)
            }
          }
          .pickerStyle(.segmented)
          .harnessNativeFormControl()
          .accessibilityLabel("Codex effort")
        }
      } else {
        TextField("Model (optional)", text: codexCustomModel)
          .harnessNativeTextField()
          .accessibilityLabel("Codex model")

        TextField("Effort (optional)", text: codexEffortText)
          .harnessNativeTextField()
          .accessibilityLabel("Codex effort")
      }
    } header: {
      Text("Codex")
        .harnessNativeFormSectionHeader()
    } footer: {
      Text("Choose the run mode, model, and effort for this draft.")
        .harnessNativeFormSectionFooter()
    }
  }

  private var codexEffortText: Binding<String> {
    Binding(
      get: { draft.codexEffort },
      set: { updateDraft(codexEffort: $0) }
    )
  }

  private func selectedTerminalModelMenuTitle(
    runtime: AgentTuiRuntime,
    catalog: RuntimeModelCatalog
  ) -> String {
    let selectedModelID = terminalModelPickerSelection(for: runtime, catalog: catalog).wrappedValue
    if selectedModelID == SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag {
      let customModelID = terminalCustomModel(for: runtime).wrappedValue
        .trimmingCharacters(in: .whitespacesAndNewlines)
      return customModelID.isEmpty ? "Custom model" : customModelID
    }

    return
      catalog.models.first { $0.id == selectedModelID }?.displayName
      ?? selectedModelID
  }

  private func selectedCodexModelMenuTitle(catalog: RuntimeModelCatalog) -> String {
    let selectedModelID = codexModelPickerSelection.wrappedValue
    if selectedModelID == SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag {
      let customModelID = codexCustomModel.wrappedValue.trimmingCharacters(
        in: .whitespacesAndNewlines
      )
      return customModelID.isEmpty ? "Custom model" : customModelID
    }

    return
      catalog.models.first { $0.id == selectedModelID }?.displayName
      ?? selectedModelID
  }

  private func terminalModelPickerSelection(
    for runtime: AgentTuiRuntime,
    catalog: RuntimeModelCatalog
  ) -> Binding<String> {
    Binding(
      get: {
        if let stored = draft.modelByRuntime[runtime.rawValue], !stored.isEmpty {
          return stored
        }
        return catalog.default
      },
      set: { newValue in
        var next = draft
        next.modelByRuntime[runtime.rawValue] = newValue
        if newValue != SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag {
          next.customModelByRuntime[runtime.rawValue] = nil
        }
        state.updateCreateDraft(next)
      }
    )
  }

  private func terminalCustomModel(
    for runtime: AgentTuiRuntime
  ) -> Binding<String> {
    Binding(
      get: { draft.customModelByRuntime[runtime.rawValue] ?? "" },
      set: {
        var next = draft
        next.modelByRuntime[runtime.rawValue] =
          SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag
        next.customModelByRuntime[runtime.rawValue] = $0
        state.updateCreateDraft(next)
      }
    )
  }

  private func terminalEffortValues(
    for runtime: AgentTuiRuntime,
    catalog: RuntimeModelCatalog
  ) -> [String] {
    SessionWindowCreateFormCatalogs.effortValues(
      catalog: catalog,
      selectedModelID: terminalModelPickerSelection(for: runtime, catalog: catalog).wrappedValue
    )
  }

  private func terminalEffortSelection(
    for runtime: AgentTuiRuntime,
    values: [String]
  ) -> Binding<String> {
    Binding(
      get: {
        guard let current = draft.effortByRuntime[runtime.rawValue], values.contains(current) else {
          return SessionWindowCreateFormCatalogs.defaultEffortLevel(from: values)
        }
        return current
      },
      set: {
        var next = draft
        next.effortByRuntime[runtime.rawValue] = $0
        state.updateCreateDraft(next)
      }
    )
  }
}
