import HarnessMonitorKit
import SwiftUI

struct SessionWindowCreateForm: View {
  let store: HarnessMonitorStore
  let state: SessionWindowStateCache
  let draft: SessionCreateDraft
  let embedsRuntimeConfiguration: Bool
  @Environment(\.fontScale)
  private var fontScale
  @State private var stateStorage = SessionWindowCreateFormStateStorage()
  @FocusState private var focusedFieldStorage: SessionWindowCreateFormField?

  var validationResult: SessionWindowCreateFormValidationResult? {
    get { stateStorage.validationResult }
    nonmutating set { stateStorage.validationResult = newValue }
  }

  var lastAutoGeneratedName: String {
    get { stateStorage.lastAutoGeneratedName }
    nonmutating set { stateStorage.lastAutoGeneratedName = newValue }
  }

  var focusedField: SessionWindowCreateFormField? {
    get { focusedFieldStorage }
    nonmutating set { focusedFieldStorage = newValue }
  }

  var focusedFieldBinding: FocusState<SessionWindowCreateFormField?>.Binding {
    $focusedFieldStorage
  }

  private var metrics: SessionWindowCreateFormMetrics {
    SessionWindowCreateFormMetrics(fontScale: fontScale)
  }

  var body: some View {
    Form {
      if draft.kind == .agent, embedsRuntimeConfiguration {
        embeddedAgentRuntimeSections
      }
      Section {
        LabeledContent("Name") {
          TextField("", text: title)
            .harnessNativeTextField()
            .focused(focusedFieldBinding, equals: .name)
            .accessibilityLabel("\(draft.kind.title) name")
            .accessibilityHint(validationMessage(for: .name) ?? "")
        }
        LabeledContent("Prompt") {
          HarnessMonitorMultilineTextField(
            placeholder: "",
            text: prompt,
            minHeight: metrics.promptMinHeight,
            focusedField: focusedFieldBinding,
            equals: .prompt,
            accessibilityLabel: "Prompt"
          )
        }
      } header: {
        HStack(spacing: HarnessMonitorTheme.spacingXS) {
          Text(draft.kind.title)
            .harnessNativeFormSectionHeader()
          Spacer(minLength: 0)

          if draft.kind == .agent {
            Button {
              regenerateAgentName()
            } label: {
              Image(systemName: "arrow.clockwise")
            }
            .harnessActionButtonStyle(variant: .bordered, tint: .secondary)
            .controlSize(HarnessMonitorControlMetrics.compactControlSize)
            .help("Generate a new agent name")
            .accessibilityLabel("Regenerate agent name")
          }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
      }
      if draft.kind == .agent {
        SessionWindowCreateBridgeBannerSection(
          store: store,
          selection: normalizedLaunchSelection
        )
      }
      if draft.kind == .agent {
        agentConfigurationSections
      }
      if draft.kind == .task {
        Section {
          Picker("Severity", selection: taskSeverity) {
            ForEach(TaskSeverity.allCases, id: \.rawValue) { severity in
              Text(severity.title).tag(severity)
            }
          }
          .accessibilityLabel("Task severity")
        } header: {
          Text("Task Details")
            .harnessNativeFormSectionHeader()
        }
      }
      if let validationResult {
        Section {
          Text(validationResult.message)
            .scaledFont(.callout)
            .foregroundStyle(.red)
            .accessibilityLabel("Validation error: \(validationResult.message)")
        }
      }
      Section {
        HStack {
          Button("Cancel", role: .cancel) {
            cancel()
          }
          Spacer()
          Button {
            Task { await submit() }
          } label: {
            Label("Create", systemImage: "plus.circle.fill")
              .scaledFont(.body.weight(.semibold))
          }
          .frame(minHeight: metrics.submitButtonMinHeight)
          .keyboardShortcut(.defaultAction)
        }
      }
    }
    .harnessNativeFormContainer()
    .contentMargins(.horizontal, metrics.formPadding, for: .scrollContent)
    .contentMargins(.vertical, metrics.formPadding, for: .scrollContent)
    .scrollContentBackground(.hidden)
    .dynamicTypeSize(.xSmall ... .accessibility5)
    .task {
      if focusedField == nil {
        focusedField = .name
      }
      prefillAgentNameIfEligible()
      if draft.kind == .agent, embedsRuntimeConfiguration {
        await SessionWindowCreateFormCatalogs.loadAgentCatalogStateIfNeeded(
          store: store,
          state: state,
          draft: draft
        )
      }
    }
    .onChange(of: draft.runtime) { _, _ in
      prefillAgentNameIfEligible()
      clearValidationIfResolved()
    }
    .onChange(of: draft.prompt) { _, _ in
      clearValidationIfResolved()
    }
  }

}

enum SessionWindowCreateFormField: Hashable {
  case name
  case prompt
  case commandOverride
}

extension SessionWindowCreateForm {
  @ViewBuilder private var agentConfigurationSections: some View {
    terminalConfigurationSections
  }

  @ViewBuilder private var embeddedAgentRuntimeSections: some View {
    Section {
      if catalogState.isLoading && !catalogState.hasLoaded {
        Label("Checking available runtimes", systemImage: "clock")
          .scaledFont(.caption)
          .foregroundStyle(HarnessMonitorTheme.secondaryInk)
      }
      if let capabilityValidation = validationMessage(for: .capability) {
        Text(capabilityValidation)
          .scaledFont(.caption)
          .foregroundStyle(.red)
          .fixedSize(horizontal: false, vertical: true)
      }

      Picker("Provider", selection: selectedProviderID) {
        ForEach(activeAgentCapabilityOptions) { option in
          Text(option.title).tag(option.id)
        }
      }
      .pickerStyle(.menu)
      .harnessNativeFormControl()
      .accessibilityLabel("Provider")
    } header: {
      Text("Provider")
        .harnessNativeFormSectionHeader()
    } footer: {
      Text(embeddedProviderDescription)
        .harnessNativeFormSectionFooter()
    }
  }

  private var embeddedProviderDescription: String {
    if let option = selectedCapabilityOption, let choice = selectedTransportChoice {
      let summary = SessionWindowCreateFormCatalogs.transportSummary(option: option, choice: choice)
      return "\(summary) Finish the remaining setup in the sections below."
    }
    return
      "Choose how this agent starts. ACP is preferred when available; the remaining "
      + "form sections hold the configuration details."
  }

  @ViewBuilder private var terminalConfigurationSections: some View {
    if let option = selectedCapabilityOption, option.transportChoices.count > 1 {
      terminalTransportChoicesSection(option: option)
    } else if !embedsRuntimeConfiguration, selectedCapabilityOption == nil {
      Section {
        Text("Choose a provider in the middle pane to configure this agent.")
          .scaledFont(.caption)
          .foregroundStyle(HarnessMonitorTheme.secondaryInk)
          .fixedSize(horizontal: false, vertical: true)
      } header: {
        Text("Provider")
          .harnessNativeFormSectionHeader()
      }
    }

    if normalizedLaunchSelection.isCodexNative {
      codexConfigurationSection
    } else {
      terminalRuntimeConfigurationSection
    }
    terminalSessionSection
    terminalAdvancedOverridesSection
  }

  private var terminalSessionSection: some View {
    Section {
      Picker("Role", selection: selectedRole) {
        ForEach(SessionRole.allCases, id: \.self) { role in
          Text(role.title).tag(role)
        }
      }
      .pickerStyle(.menu)
      .harnessNativeFormControl()
      .accessibilityLabel("Role")

      if showsAcpFallbackRoleMenu {
        Picker("Fallback role", selection: selectedFallbackRole) {
          ForEach(SessionRole.allCases.filter { $0 != .leader }, id: \.self) { role in
            Text(role.title).tag(role)
          }
        }
        .pickerStyle(.menu)
        .harnessNativeFormControl()
        .accessibilityLabel("Fallback role")
      }
      Picker("Persona", selection: selectedPersonaID) {
        Text("None").tag("")
        ForEach(activePersonas, id: \.identifier) { persona in
          Text(persona.name).tag(persona.identifier)
        }
      }
      .pickerStyle(.menu)
      .harnessNativeFormControl()
      .accessibilityLabel("Persona")
    } header: {
      Text("Session")
        .harnessNativeFormSectionHeader()
    } footer: {
      Text(
        SessionWindowCreateFormCatalogs.selectedPersonaStateText(
          personaID: draft.personaID,
          personas: activePersonas
        )
      )
      .harnessNativeFormSectionFooter()
    }
  }

  @ViewBuilder private var terminalAdvancedOverridesSection: some View {
    if !normalizedLaunchSelection.isManagedControlPlane {
      Section {
        HarnessMonitorMultilineTextField<SessionWindowCreateFormField>(
          placeholder: "",
          text: argvOverrideText,
          minHeight: 100,
          focusedField: focusedFieldBinding,
          equals: .commandOverride,
          accessibilityLabel: "Command override"
        )
      } header: {
        Text("Advanced overrides")
          .harnessNativeFormSectionHeader()
      } footer: {
        Text(advancedOverridesDescription)
          .harnessNativeFormSectionFooter()
      }
    }
  }

  private var advancedOverridesDescription: String {
    "Use one argument per line for a command override; the first line is the executable."
  }

  @ViewBuilder
  private func terminalTransportChoicesSection(option: AgentCapabilityOption) -> some View {
    if option.transportChoices.count > 1 {
      Section {
        SessionWindowCreateTransportChoicesGroup(
          option: option,
          selectedSelection: normalizedLaunchSelection,
          usesVerticalLayout: fontScale >= 1.35,
          onSelectChoice: { launchSelection.wrappedValue = $0 }
        )
        .equatable()

        if let choice = selectedTransportChoice {
          terminalTransportNotice(option: option, choice: choice)
        }
      } header: {
        Text("Start with")
          .harnessNativeFormSectionHeader()
      } footer: {
        Text("Choose whether this provider opens in Terminal or joins via ACP.")
          .harnessNativeFormSectionFooter()
      }
    }
  }

  @ViewBuilder private var terminalRuntimeConfigurationSection: some View {
    let option = selectedCapabilityOption
    let choice = selectedTransportChoice

    Section {
      if let catalog = selectedRuntimeCatalog,
        let runtimeKey = selectedModelCatalogRuntimeKey
      {
        let modelPickerValue = currentRuntimeModelPickerValue(
          for: runtimeKey,
          catalog: catalog
        )
        let effortValues = runtimeEffortValues(
          for: runtimeKey,
          catalog: catalog
        )
        SessionWindowCreateRuntimeModelPickerRow(
          catalog: catalog,
          modelPickerValue: modelPickerValue,
          onModelChange: { updateRuntimeModelPickerSelection($0, for: runtimeKey) }
        )
        .equatable()

        if modelPickerValue == SessionWindowCreateFormCatalogs.RuntimeCustomModel.tag {
          SessionWindowCreateRuntimeCustomModelRow(
            customModel: currentRuntimeCustomModel(for: runtimeKey),
            onCustomModelChange: { updateRuntimeCustomModel($0, for: runtimeKey) }
          )
          .equatable()
        }

        if !effortValues.isEmpty {
          SessionWindowCreateRuntimeEffortRow(
            values: effortValues,
            selectedEffort: resolvedRuntimeEffortSelection(
              for: runtimeKey,
              values: effortValues
            ),
            onEffortChange: { updateRuntimeEffort($0, for: runtimeKey) }
          )
          .equatable()
        }
      } else if normalizedLaunchSelection.isAcp {
        Text("ACP uses the provider's configured defaults.")
          .scaledFont(.caption)
          .foregroundStyle(HarnessMonitorTheme.secondaryInk)
          .fixedSize(horizontal: false, vertical: true)
      } else {
        Text("This runtime does not publish additional model controls here.")
          .scaledFont(.caption)
          .foregroundStyle(HarnessMonitorTheme.secondaryInk)
          .fixedSize(horizontal: false, vertical: true)
      }

      if let option, let choice, option.transportChoices.count <= 1 {
        terminalTransportNotice(option: option, choice: choice)
      }
    } header: {
      Text("Runtime")
        .harnessNativeFormSectionHeader()
    } footer: {
      if let option, let choice {
        Text(SessionWindowCreateFormCatalogs.transportSummary(option: option, choice: choice))
          .harnessNativeFormSectionFooter()
      }
    }
  }

}
