import HarnessMonitorKit
import OSLog

private let logger = Logger(
  subsystem: "io.harnessmonitor",
  category: "AgentNameGenerator"
)

extension SessionWindowCreateForm {
  func prefillAgentNameIfEligible() {
    guard draft.kind == .agent else { return }
    let trimmed = draft.title.trimmingCharacters(in: .whitespacesAndNewlines)
    let regenerable = trimmed.isEmpty || draft.title == lastAutoGeneratedName
    guard regenerable else { return }
    apply(
      AgentNameGenerator.generate(
        for: agentNameRuntime,
        avoiding: lastAutoGeneratedName.isEmpty ? nil : lastAutoGeneratedName,
        excluding: existingAgentNamesInSession()
      )
    )
  }

  func regenerateAgentName() {
    guard draft.kind == .agent else { return }
    apply(
      AgentNameGenerator.generate(
        for: agentNameRuntime,
        avoiding: draft.title.isEmpty ? nil : draft.title,
        excluding: existingAgentNamesInSession()
      )
    )
  }

  private var agentNameRuntime: AgentTuiRuntime {
    if draft.useCodex {
      return .codex
    }
    return draft.launchSelection.preferredRuntime
  }

  private func existingAgentNamesInSession() -> [String] {
    (store.selectedSession?.agents ?? [])
      .map(\.name)
      .filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
  }

  private func apply(_ outcome: AgentNameGenerator.Outcome) {
    switch outcome {
    case .generated(let name):
      updateDraft(title: name)
      lastAutoGeneratedName = name
    case .exhausted(let fallback, let runtime):
      logger.info(
        """
        name generator exhausted runtime=\(runtime.rawValue, privacy: .public) \
        fallback=\(fallback, privacy: .public)
        """
      )
      updateDraft(title: fallback)
      lastAutoGeneratedName = fallback
    }
  }
}
