import HarnessMonitorKit
import SwiftUI

struct SessionWindowCreateFormMetrics: Equatable {
  let formPadding: CGFloat
  let promptMinHeight: CGFloat
  let submitButtonMinHeight: CGFloat

  init(fontScale: CGFloat) {
    let scale = SessionWindowFontScale.metricsScale(for: fontScale)
    formPadding = 24 * min(scale, 1.3)
    promptMinHeight = max(90, 90 * min(scale, 1.25))
    submitButtonMinHeight = scale >= 1.45 ? 44 : 0
  }
}

struct SessionWindowCreateFormStateStorage {
  var validationResult: SessionWindowCreateFormValidationResult?
  var lastAutoGeneratedName = ""
  var openRouterModels: [OpenRouterModelEntry] = []
  var openRouterUsageSnapshot: OpenRouterModelUsageSnapshot = .empty
  var isLoadingOpenRouterModels = false
  var isPresentingOpenRouterBrowser = false
  var openRouterModelsLoadedFor: String?
}

extension SessionWindowCreateForm {
  func updateDraft(
    title: String? = nil,
    prompt: String? = nil,
    runtime: String? = nil,
    role: SessionRole? = nil,
    fallbackRole: SessionRole? = nil,
    personaID: String? = nil,
    argvOverride: String? = nil,
    taskSeverity: TaskSeverity? = nil,
    codexMode: CodexRunMode? = nil,
    codexModel: String? = nil,
    codexEffort: String? = nil,
    codexAllowCustomModel: Bool? = nil
  ) {
    var next = draft
    next.title = title ?? next.title
    next.prompt = prompt ?? next.prompt
    next.runtime = runtime ?? next.runtime
    next.role = role ?? next.role
    next.fallbackRole = fallbackRole ?? next.fallbackRole
    next.personaID = personaID ?? next.personaID
    next.argvOverride = argvOverride ?? next.argvOverride
    next.taskSeverity = taskSeverity ?? next.taskSeverity
    next.codexMode = codexMode ?? next.codexMode
    next.codexModel = codexModel ?? next.codexModel
    next.codexEffort = codexEffort ?? next.codexEffort
    next.codexAllowCustomModel = codexAllowCustomModel ?? next.codexAllowCustomModel
    clearValidationIfNeeded(title: title, runtime: runtime)
    state.updateCreateDraft(next)
  }

  func cancel() {
    validationResult = nil
    state.cancelCreateDraft(draft.kind)
  }
}
