[package]
name = "harness-task-board-workflow-execution"
version = "57.0.0"
edition = "2024"
rust-version = "1.95"
publish = false

[dependencies]
chrono = "0.4.44"
harness-kernel = { path = "../harness-kernel", version = "57.0.0" }
harness-task-board = { path = "../harness-task-board", version = "57.0.0" }

[lints.clippy]
pedantic = { level = "deny", priority = 1 }

[lints.rust]
unused = { level = "deny", priority = 1 }
