use std::fmt;

use crate::observe::types::{Confidence, FixSafety, IssueCategory, IssueCode, IssueSeverity};

/// Responsibility owner for an issue code.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IssueOwner {
    /// Harness CLI or infrastructure bug.
    Harness,
    /// Skill file or skill behavior defect.
    Skill,
    /// Possible upstream product bug (Kuma, CRD, webhook).
    Product,
    /// Model misbehavior (Claude, subagent).
    Model,
}

impl fmt::Display for IssueOwner {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Harness => "harness",
            Self::Skill => "skill",
            Self::Product => "product",
            Self::Model => "model",
        })
    }
}

/// Static metadata for a single issue code.
pub struct IssueCodeMeta {
    pub code: IssueCode,
    pub default_category: IssueCategory,
    pub default_severity: IssueSeverity,
    pub default_confidence: Confidence,
    pub default_fix_safety: FixSafety,
    pub description: &'static str,
    pub owner: IssueOwner,
}

/// Centralized registry of all issue codes with their default metadata.
///
/// One entry per `IssueCode` variant. The values here reflect the defaults
/// used by the classifier rules and text checks - individual emit sites may
/// override confidence or `fix_safety` contextually.
static ISSUE_CODE_REGISTRY: &[IssueCodeMeta] = &[
    // ─── Hook / guard issues ───────────────────────────────────────
    IssueCodeMeta {
        code: IssueCode::HookDeniedToolCall,
        default_category: IssueCategory::HookFailure,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::TriageRequired,
        description: "Hook denied a tool call",
        owner: IssueOwner::Harness,
    },
    IssueCodeMeta {
        code: IssueCode::HarnessHookCodeTriggered,
        default_category: IssueCategory::HookFailure,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Harness hook code (KSA/KSR) triggered in output",
        owner: IssueOwner::Harness,
    },
    // ─── CLI errors ────────────────────────────────────────────────
    IssueCodeMeta {
        code: IssueCode::HarnessCliErrorOutput,
        default_category: IssueCategory::CliError,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Harness CLI returned an error in command output",
        owner: IssueOwner::Harness,
    },
    IssueCodeMeta {
        code: IssueCode::InvalidHarnessSubcommandUsed,
        default_category: IssueCategory::CliError,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Non-existent harness subcommand or argument used",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::RunnerStateEventNotSupported,
        default_category: IssueCategory::CliError,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "runner-state event transition not supported via CLI",
        owner: IssueOwner::Harness,
    },
    // ─── Tool errors ───────────────────────────────────────────────
    IssueCodeMeta {
        code: IssueCode::ToolUsageErrorOutput,
        default_category: IssueCategory::ToolError,
        default_severity: IssueSeverity::Low,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "Claude tool usage error in output",
        owner: IssueOwner::Model,
    },
    // ─── Build errors ──────────────────────────────────────────────
    IssueCodeMeta {
        code: IssueCode::BuildOrLintFailure,
        default_category: IssueCategory::BuildError,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Rust build or clippy lint failure",
        owner: IssueOwner::Harness,
    },
    IssueCodeMeta {
        code: IssueCode::PythonTracebackOutput,
        default_category: IssueCategory::BuildError,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixGuarded,
        description: "Python traceback in command output",
        owner: IssueOwner::Model,
    },
    // ─── Workflow errors ───────────────────────────────────────────
    IssueCodeMeta {
        code: IssueCode::WorkflowStateErrorOutput,
        default_category: IssueCategory::WorkflowError,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixGuarded,
        description: "Workflow state machine error in output",
        owner: IssueOwner::Harness,
    },
    IssueCodeMeta {
        code: IssueCode::HarnessAuthoringCommandFailure,
        default_category: IssueCategory::WorkflowError,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixGuarded,
        description: "Harness authoring command returned non-zero exit",
        owner: IssueOwner::Harness,
    },
    IssueCodeMeta {
        code: IssueCode::CloseoutVerdictPending,
        default_category: IssueCategory::WorkflowError,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Closeout blocked because no final verdict was set",
        owner: IssueOwner::Harness,
    },
    IssueCodeMeta {
        code: IssueCode::RunnerStateMachineStale,
        default_category: IssueCategory::WorkflowError,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::AutoFixGuarded,
        description: "Runner state machine never advanced past bootstrap",
        owner: IssueOwner::Harness,
    },
    IssueCodeMeta {
        code: IssueCode::HarnessInfrastructureMisconfiguration,
        default_category: IssueCategory::WorkflowError,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::TriageRequired,
        description: "Harness infrastructure misconfiguration detected",
        owner: IssueOwner::Harness,
    },
    // ─── Data integrity ────────────────────────────────────────────
    IssueCodeMeta {
        code: IssueCode::PodContainerRuntimeFailure,
        default_category: IssueCategory::DataIntegrity,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::TriageRequired,
        description: "Pod or container failure at runtime - possible product bug",
        owner: IssueOwner::Product,
    },
    IssueCodeMeta {
        code: IssueCode::PayloadWrappedInJsonTags,
        default_category: IssueCategory::DataIntegrity,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixGuarded,
        description: "Payload wrapped in XML-style <json> tags by subagent",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::ManifestRuntimeFailure,
        default_category: IssueCategory::DataIntegrity,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::TriageRequired,
        description: "Manifest operation failed at runtime - possible product bug",
        owner: IssueOwner::Product,
    },
    IssueCodeMeta {
        code: IssueCode::MissingClaudeSessionId,
        default_category: IssueCategory::DataIntegrity,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "CLAUDE_SESSION_ID env var is unset",
        owner: IssueOwner::Harness,
    },
    IssueCodeMeta {
        code: IssueCode::ManifestFixPromptShown,
        default_category: IssueCategory::DataIntegrity,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::TriageRequired,
        description: "Manifest rejected by cluster - CRD/webhook mismatch",
        owner: IssueOwner::Product,
    },
    IssueCodeMeta {
        code: IssueCode::JqErrorInCommandOutput,
        default_category: IssueCategory::DataIntegrity,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "jq parse or iteration error in command output",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::MissingConnectionOrEnvVar,
        default_category: IssueCategory::DataIntegrity,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "Missing configuration or connection acknowledged by assistant",
        owner: IssueOwner::Harness,
    },
    // ─── Skill behavior ────────────────────────────────────────────
    IssueCodeMeta {
        code: IssueCode::DirectKubectlValidateUsage,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "kubectl-validate used directly instead of harness authoring-validate",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::SuiteDeviationDetected,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::TriageRequired,
        description: "Suite deviation - baselines or manifests not fully distributed",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::ReleaseKumactlBinaryUsed,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Release kumactl binary used instead of worktree build",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::EmptyKubeconfig,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "KUBECONFIG is empty - cluster commands will hit default context",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::ValidatorInstallPromptShown,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::AutoFixGuarded,
        description: "Validator install prompt when binary may already exist",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::RuntimeDeviationPromptShown,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::TriageRequired,
        description: "Runtime deviation prompt - authored suite needs runtime correction",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::WrongSkillCrossReference,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "suite:run offering suite:new as a structured choice",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::ShortSkillNameInSkillFile,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "SKILL.md name field uses colon-prefixed form instead of short name",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::ManifestCreatedDuringRun,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::TriageRequired,
        description: "Manifest YAML created during run - should be authored in suite:new",
        owner: IssueOwner::Skill,
    },
    // ─── Unexpected behavior ───────────────────────────────────────
    IssueCodeMeta {
        code: IssueCode::AuthFlowTriggered,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "OAuth/auth flow triggered - command tried to reach a real cluster",
        owner: IssueOwner::Harness,
    },
    IssueCodeMeta {
        code: IssueCode::ShellAliasInterference,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "Shell alias interference - rsync appeared in cp output",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::PythonUsedInBashOutput,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Python used in Bash output - agents should never need python",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::CorporateClusterContextDetected,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Corporate or remote cluster context detected instead of local k3d",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::PythonUsedInBashToolUse,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Python invoked in Bash tool_use command",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::UnverifiedRecursiveRemove,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "Destructive rm -r without chained verification",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::RawClusterMakeTargetUsed,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Raw make k3d/kind target used instead of harness setup kuma cluster",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::UnauthorizedGitCommitDuringRun,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Low,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "Git commit observed during active run (advisory - UI approval gate handles enforcement)",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::ManualKubeconfigConstruction,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Agent manually setting KUBECONFIG env var",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::ManualExportConstruction,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Agent constructing env vars via export",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::ManualEnvPrefixConstruction,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Agent constructing VAR=value env prefix on command",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::FileEditChurn,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "File modified many times - possible trial-and-error churn",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::AbsoluteManifestPathUsed,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Absolute path used with harness apply instead of relative",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::DirectManagedFileWrite,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Critical,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Direct write to harness-managed file via Write/Edit tool",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::DirectTaskOutputFileRead,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Direct read of internal Claude task output file",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::SleepPrefixBeforeHarnessCommand,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Low,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Sleep prefix before harness command instead of --delay flag",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::RepeatedKubectlQueryForSameResource,
        default_category: IssueCategory::UnexpectedBehavior,
        default_severity: IssueSeverity::Low,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "Same kubectl resource queried multiple times instead of dumping once",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::UncommittedSourceCodeEdit,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::TriageRequired,
        description: "Source code edited without committing before next action",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::ResourceNotCleanedUpBeforeGroupEnd,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Low,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "Resources created during group not cleaned up before group end",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::GroupReportedWithoutCapture,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Group reported without a state capture for that group",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::VerificationOutputTruncated,
        default_category: IssueCategory::SkillBehavior,
        default_severity: IssueSeverity::Low,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "Verification command output truncated by tail/head pipe",
        owner: IssueOwner::Model,
    },
    // ─── Subagent issues ───────────────────────────────────────────
    IssueCodeMeta {
        code: IssueCode::NonZeroExitCode,
        default_category: IssueCategory::SubagentIssue,
        default_severity: IssueSeverity::Low,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "Non-zero exit code from a command",
        owner: IssueOwner::Model,
    },
    IssueCodeMeta {
        code: IssueCode::SubagentPermissionFailure,
        default_category: IssueCategory::SubagentIssue,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Subagent blocked by missing permissions",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::SubagentManualRecovery,
        default_category: IssueCategory::SubagentIssue,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::AutoFixGuarded,
        description: "Subagent required manual recovery after save failure",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::ManualPayloadRecovery,
        default_category: IssueCategory::SubagentIssue,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::Low,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "Manual payload recovery from subagent output via grep",
        owner: IssueOwner::Skill,
    },
    IssueCodeMeta {
        code: IssueCode::IncompleteWriterOutput,
        default_category: IssueCategory::SubagentIssue,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::Medium,
        default_fix_safety: FixSafety::AutoFixGuarded,
        description: "Writer subagent produced incomplete output",
        owner: IssueOwner::Skill,
    },
    // ─── Naming errors ─────────────────────────────────────────────
    IssueCodeMeta {
        code: IssueCode::OldSkillNameUsedInCommand,
        default_category: IssueCategory::NamingError,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::High,
        default_fix_safety: FixSafety::AutoFixSafe,
        description: "Old skill name (suite-author/suite-runner) used in command",
        owner: IssueOwner::Skill,
    },
    // ─── User frustration ──────────────────────────────────────────
    IssueCodeMeta {
        code: IssueCode::UserFrustrationDetected,
        default_category: IssueCategory::UserFrustration,
        default_severity: IssueSeverity::Medium,
        default_confidence: Confidence::Low,
        default_fix_safety: FixSafety::AdvisoryOnly,
        description: "User frustration signal detected in message",
        owner: IssueOwner::Model,
    },
];

/// Look up the static metadata for an issue code.
///
/// Returns `None` only if the code is missing from the registry (a bug).
#[must_use]
pub fn issue_code_meta(code: IssueCode) -> Option<&'static IssueCodeMeta> {
    ISSUE_CODE_REGISTRY.iter().find(|entry| entry.code == code)
}

#[cfg(test)]
#[path = "registry/tests.rs"]
mod tests;
