import HarnessMonitorKit
import OSLog

private let logger = Logger(
  subsystem: "io.harnessmonitor",
  category: "AgentNameGenerator"
)

extension WorkspaceWindowCreatePane {
  func prefillAgentNameIfEligible() {
    Self.prefillAgentNameIfEligible(
      viewModel: viewModel,
      taken: existingAgentNamesInSession()
    )
  }

  func regenerateAgentName() {
    Self.regenerateAgentName(
      viewModel: viewModel,
      taken: existingAgentNamesInSession()
    )
  }

  var agentNameValidationWarning: String? {
    Self.agentNameValidationWarning(
      viewModel: viewModel,
      taken: existingAgentNamesInSession()
    )
  }

  func existingAgentNamesInSession() -> [String] {
    (store.selectedSession?.agents ?? [])
      .map(\.name)
      .filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
  }
}

extension WorkspaceWindowCreatePane {
  @MainActor
  static func prefillAgentNameIfEligible(
    viewModel: ViewModel,
    taken: [String]
  ) {
    let trimmed = viewModel.name.trimmingCharacters(in: .whitespacesAndNewlines)
    let regenerable = trimmed.isEmpty || viewModel.name == viewModel.lastAutoGeneratedName
    guard regenerable else { return }
    apply(
      AgentNameGenerator.generate(
        for: viewModel.selectedLaunchSelection.preferredRuntime,
        avoiding: viewModel.lastAutoGeneratedName,
        excluding: taken
      ),
      to: viewModel
    )
  }

  @MainActor
  static func regenerateAgentName(
    viewModel: ViewModel,
    taken: [String]
  ) {
    apply(
      AgentNameGenerator.generate(
        for: viewModel.selectedLaunchSelection.preferredRuntime,
        avoiding: viewModel.name,
        excluding: taken
      ),
      to: viewModel
    )
  }

  static func agentNameValidationWarning(
    viewModel: ViewModel,
    taken: [String]
  ) -> String? {
    let trimmed = viewModel.name.trimmingCharacters(in: .whitespacesAndNewlines)
    if trimmed.isEmpty {
      return "Display name is required."
    }
    if taken.contains(where: { $0.caseInsensitiveCompare(trimmed) == .orderedSame }) {
      return "An agent with this name already exists in the session."
    }
    return nil
  }

  @MainActor
  private static func apply(
    _ outcome: AgentNameGenerator.Outcome,
    to viewModel: ViewModel
  ) {
    switch outcome {
    case .generated(let name):
      viewModel.name = name
      viewModel.lastAutoGeneratedName = name
    case .exhausted(let fallback, let runtime):
      logger.info(
        """
        name generator exhausted runtime=\(runtime.rawValue, privacy: .public) \
        fallback=\(fallback, privacy: .public)
        """
      )
      viewModel.name = fallback
      viewModel.lastAutoGeneratedName = fallback
    }
  }
}
