import HarnessMonitorPolicyModels

public typealias TaskBoardPolicyAction = HarnessMonitorPolicyModels.TaskBoardPolicyAction
public typealias TaskBoardPolicyEvidenceField = HarnessMonitorPolicyModels
  .TaskBoardPolicyEvidenceField
public typealias TaskBoardPolicyPipelineAutomationBinding =
  HarnessMonitorPolicyModels.TaskBoardPolicyPipelineAutomationBinding
public typealias TaskBoardPolicyPipelineOCRConfiguration =
  HarnessMonitorPolicyModels.TaskBoardPolicyPipelineOCRConfiguration
public typealias TaskBoardPolicyPipelineReviewPullRequestExtraction =
  HarnessMonitorPolicyModels.TaskBoardPolicyPipelineReviewPullRequestExtraction
public typealias TaskBoardPolicyEvidencePredicateValue =
  HarnessMonitorPolicyModels.TaskBoardPolicyEvidencePredicateValue
public typealias TaskBoardPolicyEvidencePredicate =
  HarnessMonitorPolicyModels.TaskBoardPolicyEvidencePredicate
public typealias TaskBoardPolicyEvidenceCheck =
  HarnessMonitorPolicyModels.TaskBoardPolicyEvidenceCheck
public typealias TaskBoardPolicySwitchArm = HarnessMonitorPolicyModels.TaskBoardPolicySwitchArm
public typealias TaskBoardPolicyWaitCondition = HarnessMonitorPolicyModels
  .TaskBoardPolicyWaitCondition
public typealias TaskBoardPolicyPipelineNodeKind =
  HarnessMonitorPolicyModels.TaskBoardPolicyPipelineNodeKind
public typealias TaskBoardPolicyPipelineNodeLayoutSource =
  HarnessMonitorPolicyModels.TaskBoardPolicyPipelineNodeLayoutSource
public typealias TaskBoardPolicyPipelineValidation =
  HarnessMonitorPolicyModels.TaskBoardPolicyPipelineValidation
public typealias TaskBoardPolicyPipelineValidationIssue =
  HarnessMonitorPolicyModels.TaskBoardPolicyPipelineValidationIssue
public typealias TaskBoardPolicyDecision = HarnessMonitorPolicyModels.TaskBoardPolicyDecision
public typealias TaskBoardPolicyPipelineSimulatedDecision =
  HarnessMonitorPolicyModels.TaskBoardPolicyPipelineSimulatedDecision
public typealias TaskBoardPolicyPipelineSimulationResult =
  HarnessMonitorPolicyModels.TaskBoardPolicyPipelineSimulationResult
